"""Accepted-photo production drawable tests with mock Android, no device execution."""
from pathlib import Path
import subprocess,re,json,shutil

HOST_FILES={'android/content/res/Resources.java': 'package android.content.res;public class Resources{public '
                                       'android.util.DisplayMetrics metrics=new '
                                       'android.util.DisplayMetrics();public '
                                       'android.util.DisplayMetrics getDisplayMetrics(){return '
                                       'metrics;}}',
 'android/graphics/Canvas.java': 'package android.graphics;public class Canvas{public '
                                 'java.util.List<Entry> ops=new java.util.ArrayList<>();public '
                                 'RectF clip;public static class Entry{public RectF rect;public '
                                 'int color,alpha;public Paint.Style style;public float '
                                 'stroke;Entry(RectF r,Paint '
                                 'p){rect=r;color=p.color;alpha=p.alpha;style=p.style;stroke=p.stroke;}}public '
                                 'int save(){return 1;}public boolean clipRect(RectF '
                                 'r){clip=r;return true;}public void drawRect(RectF r,Paint '
                                 'p){ops.add(new Entry(r,p));}public void drawRect(float a,float '
                                 'b,float c,float d,Paint p){drawRect(new '
                                 'RectF(a,b,c,d),p);}public void restoreToCount(int saved){}}',
 'android/graphics/Color.java': 'package android.graphics;public class Color{public static final '
                                'int BLACK=0xff000000,WHITE=0xffffffff;}',
 'android/graphics/ColorFilter.java': 'package android.graphics;public class ColorFilter{}',
 'android/graphics/Paint.java': 'package android.graphics;public class Paint{public static final '
                                'int ANTI_ALIAS_FLAG=1;public enum Style{FILL,STROKE};public int '
                                'color,alpha;public Style style;public float stroke;public '
                                'Paint(int flags){}public void setStyle(Style x){style=x;}public '
                                'void setColor(int x){color=x;alpha=x>>>24;}public void '
                                'setAlpha(int x){alpha=x;}public void setStrokeWidth(float '
                                'x){stroke=x;}}',
 'android/graphics/PixelFormat.java': 'package android.graphics;public class PixelFormat{public '
                                      'static final int TRANSLUCENT=-3;}',
 'android/graphics/RectF.java': 'package android.graphics;public class RectF {public float '
                                'left,top,right,bottom;public RectF(float l,float t,float r,float '
                                'b){left=l;top=t;right=r;bottom=b;}}',
 'android/graphics/drawable/Drawable.java': 'package android.graphics.drawable;public abstract '
                                            'class Drawable{public int '
                                            'left,top,right,bottom;public void setBounds(int a,int '
                                            'b,int c,int d){left=a;top=b;right=c;bottom=d;}public '
                                            'abstract void draw(android.graphics.Canvas c);public '
                                            'abstract void setAlpha(int a);public abstract void '
                                            'setColorFilter(android.graphics.ColorFilter c);public '
                                            'abstract int getOpacity();}',
 'android/os/Looper.java': 'package android.os;public class Looper {static Looper main=new '
                           'Looper();public static boolean worker;public static Looper '
                           'myLooper(){return worker?null:main;}public static Looper '
                           'getMainLooper(){return main;}}',
 'android/os/SystemClock.java': 'package android.os;public class SystemClock{public static long '
                                'now=5000;public static long uptimeMillis(){return now;}}',
 'android/util/DisplayMetrics.java': 'package android.util;public class DisplayMetrics{public '
                                     'float density=1;}',
 'android/view/View.java': 'package android.view;public class View {public boolean '
                           'attached=true,shown=true,enabled=true,focus=true;public int '
                           'visibility=0,clearAnimations=0,invalidations=0;public boolean '
                           'schedule=true;public boolean failOverlay;public '
                           'java.util.LinkedHashMap<Runnable,Long> callbacks=new '
                           'java.util.LinkedHashMap<>();public android.view.ViewOverlay '
                           'overlay=new android.view.ViewOverlay();public '
                           'android.content.res.Resources resources=new '
                           'android.content.res.Resources();public interface '
                           'OnAttachStateChangeListener {void onViewAttachedToWindow(View v);void '
                           'onViewDetachedFromWindow(View v);}public '
                           'java.util.ArrayList<OnAttachStateChangeListener> listeners=new '
                           'java.util.ArrayList<>();public void '
                           'addOnAttachStateChangeListener(OnAttachStateChangeListener '
                           'l){if(!listeners.contains(l))listeners.add(l);}public void '
                           'removeOnAttachStateChangeListener(OnAttachStateChangeListener '
                           'l){listeners.remove(l);}public void '
                           'detach(){attached=false;for(OnAttachStateChangeListener l:new '
                           'java.util.ArrayList<>(listeners))l.onViewDetachedFromWindow(this);}public '
                           'void attach(){attached=true;for(OnAttachStateChangeListener l:new '
                           'java.util.ArrayList<>(listeners))l.onViewAttachedToWindow(this);}public '
                           'View root=this;public int width=1080,height=2340,sx=0,sy=24;public '
                           'boolean isAttachedToWindow(){return attached;}public boolean '
                           'isShown(){return shown;}public boolean isEnabled(){return '
                           'enabled;}public boolean hasWindowFocus(){return focus;}public View '
                           'getRootView(){return root;}public int getWidth(){return width;}public '
                           'int getHeight(){return height;}public void getLocationOnScreen(int[] '
                           'x){x[0]=sx;x[1]=sy;}public static final int GONE=8;public '
                           'android.content.res.Resources getResources(){return resources;}public '
                           'android.view.ViewOverlay getOverlay(){if(failOverlay)throw new '
                           'IllegalStateException("overlay unavailable");return overlay;}public '
                           'void clearAnimation(){clearAnimations++;}public void setVisibility(int '
                           'v){visibility=v;}public boolean removeCallbacks(Runnable r){return '
                           'callbacks.remove(r)!=null;}public boolean postDelayed(Runnable r,long '
                           't){if(schedule)callbacks.put(r,android.os.SystemClock.now+t);return '
                           'schedule;}public void '
                           'postInvalidateOnAnimation(){invalidations++;}public void '
                           'invalidate(){invalidations++;}}',
 'android/view/ViewOverlay.java': 'package android.view;public class ViewOverlay{public '
                                  'java.util.ArrayList<android.graphics.drawable.Drawable> '
                                  'drawables=new java.util.ArrayList<>();public void '
                                  'add(android.graphics.drawable.Drawable '
                                  'd){if(!drawables.contains(d))drawables.add(d);}public void '
                                  'remove(android.graphics.drawable.Drawable '
                                  'd){drawables.remove(d);}}',
 'com/bytedance/corecamera/ui/view/CameraShadeView.java': 'package '
                                                          'com.bytedance.corecamera.ui.view;public '
                                                          'class CameraShadeView extends '
                                                          'android.view.View {public Object '
                                                          'w;public int c=1080,j=2340;public '
                                                          'android.graphics.RectF n=new '
                                                          'android.graphics.RectF(0,0,1080,60),o=new '
                                                          'android.graphics.RectF(0,1500,1080,2340);}',
 'com/hiro/ulike/FeedbackTests1941.java': 'package com.hiro.ulike;\n'
                                          'import android.os.*;import android.view.*;import '
                                          'android.graphics.*;import '
                                          'android.graphics.drawable.*;import '
                                          'com.bytedance.corecamera.ui.view.*;\n'
                                          'public final class FeedbackTests1941 {\n'
                                          ' static int count;static CameraShadeView shade;static '
                                          'View nativeFlash;static View frontFill;\n'
                                          ' static void ck(String n,boolean ok){if(!ok)throw new '
                                          'AssertionError(n);count++;System.out.println("PASS\\t"+n);}\n'
                                          ' static void '
                                          'setup(){Looper.worker=false;SystemClock.now+=1000;shade=new '
                                          'CameraShadeView();nativeFlash=new '
                                          'View();nativeFlash.root=shade;frontFill=new '
                                          'View();PreviewLayout1922.view=shade;PreviewLayout1922.rect=new '
                                          'RectF(0,60,1080,1500);}\n'
                                          ' static Canvas frame(){Canvas canvas=new '
                                          'Canvas();shade.overlay.drawables.get(0).draw(canvas);return '
                                          'canvas;}\n'
                                          ' static void fallback(String '
                                          'n){ck(n,!ShutterFeedback1941.show(nativeFlash)&&nativeFlash.visibility==0&&nativeFlash.clearAnimations==0&&shade.overlay.drawables.isEmpty());}\n'
                                          ' public static void main(String[] args){\n'
                                          '  setup();ck("accepted photo shows '
                                          'frame",ShutterFeedback1941.show(nativeFlash));\n'
                                          '  ck("replaces original white mask only after '
                                          'readiness",nativeFlash.visibility==8&&nativeFlash.clearAnimations==1);\n'
                                          '  ck("single drawable overlay never adds input '
                                          'view",shade.overlay.drawables.size()==1);\n'
                                          '  ck("front fill light '
                                          'untouched",frontFill.visibility==0&&frontFill.clearAnimations==0&&frontFill.callbacks.isEmpty());\n'
                                          '  Canvas c=frame();ck("one tint plus dark and white '
                                          'outline",c.ops.size()==3);\n'
                                          '  ck("preview remains visible through 12 percent '
                                          'tint",c.ops.get(0).alpha==31&&c.ops.get(0).style==Paint.Style.FILL);\n'
                                          '  ck("bright frame uses dark '
                                          'edge",c.ops.get(1).color==Color.BLACK&&c.ops.get(1).alpha==230&&c.ops.get(2).color==Color.WHITE&&c.ops.get(2).alpha==255);\n'
                                          '  ck("five dp frame, eight dp outer '
                                          'edge",c.ops.get(1).stroke==8&&c.ops.get(2).stroke==5);\n'
                                          '  ck("frame limited to preview, black controls '
                                          'excluded",c.clip.left==0&&c.clip.top==60&&c.clip.right==1080&&c.clip.bottom==1500);\n'
                                          '  ck("hold protects cue from imperceptible '
                                          'blink",ShutterFeedback1941.strength(0)==1&&ShutterFeedback1941.strength(110)==1);\n'
                                          '  SystemClock.now+=165;c=frame();ck("smooth fade after '
                                          'hold",c.ops.get(2).alpha>0&&c.ops.get(2).alpha<255);\n'
                                          '  ck("fade endpoints '
                                          'bounded",ShutterFeedback1941.strength(-1)==0&&ShutterFeedback1941.strength(319)>0&&ShutterFeedback1941.strength(320)==0);\n'
                                          '  Runnable '
                                          'old=shade.callbacks.keySet().iterator().next();SystemClock.now+=155;old.run();ck("320ms '
                                          'completion frees overlay and '
                                          'callbacks",shade.overlay.drawables.isEmpty()&&shade.callbacks.isEmpty()&&shade.listeners.isEmpty());\n'
                                          '  '
                                          'setup();ShutterFeedback1941.show(nativeFlash);old=shade.callbacks.keySet().iterator().next();SystemClock.now+=80;ck("quick '
                                          'accepted repeat restarts '
                                          'pulse",ShutterFeedback1941.show(nativeFlash)&&shade.overlay.drawables.size()==1&&shade.callbacks.size()==1);\n'
                                          '  SystemClock.now+=240;old.run();ck("old callback '
                                          'cannot erase new '
                                          'cue",shade.overlay.drawables.size()==1&&shade.callbacks.size()==1);\n'
                                          '  ck("new cue owns updated '
                                          'deadline",shade.callbacks.values().iterator().next()==SystemClock.now+80);\n'
                                          '  SystemClock.now+=80;old.run();ck("new deadline '
                                          'removes '
                                          'cue",shade.overlay.drawables.isEmpty()&&shade.callbacks.isEmpty());\n'
                                          '  setup();shade.w=new '
                                          'Object();shade.n.bottom=309;shade.o.top=1800;ck("transition '
                                          'uses actual drawn '
                                          'bounds",ShutterFeedback1941.show(nativeFlash)&&frame().clip.top==309&&frame().clip.bottom==1800);\n'
                                          '  setup();Looper.worker=true;fallback("off-main returns '
                                          'native fallback with mask '
                                          'untouched");Looper.worker=false;\n'
                                          '  setup();shade.attached=false;fallback("detached '
                                          'native fallback");\n'
                                          '  setup();shade.shown=false;fallback("hidden shade '
                                          'native fallback");\n'
                                          '  setup();shade.focus=false;fallback("unfocused native '
                                          'fallback");\n'
                                          '  setup();nativeFlash.root=new View();fallback("other '
                                          'window native fallback");\n'
                                          '  setup();PreviewLayout1922.rect=null;fallback("missing '
                                          'geometry native fallback");\n'
                                          '  setup();PreviewLayout1922.rect=new '
                                          'RectF(0,60,1081,1500);fallback("invalid geometry native '
                                          'fallback");\n'
                                          '  setup();PreviewLayout1922.rect=new '
                                          'RectF(Float.NaN,60,1080,1500);fallback("NaN geometry '
                                          'native fallback");\n'
                                          '  setup();PreviewLayout1922.view=null;fallback("missing '
                                          'shade native fallback");\n'
                                          '  setup();shade.width=0;fallback("unmeasured view '
                                          'native fallback");\n'
                                          '  setup();shade.schedule=false;fallback("unscheduled '
                                          'cleanup rejects custom feedback");\n'
                                          '  setup();shade.failOverlay=true;fallback("exception '
                                          'permits original native '
                                          'blink");shade.failOverlay=false;ck("exception cleanup '
                                          'permits later normal '
                                          'cue",ShutterFeedback1941.show(nativeFlash)&&shade.overlay.drawables.size()==1);\n'
                                          '  setup();ck("null native view '
                                          'safe",!ShutterFeedback1941.show(null)&&shade.overlay.drawables.isEmpty());\n'
                                          '  '
                                          'setup();ShutterFeedback1941.show(nativeFlash);old=shade.callbacks.keySet().iterator().next();shade.detach();ck("detachment '
                                          'immediately cleans '
                                          'pulse",shade.overlay.drawables.isEmpty()&&shade.callbacks.isEmpty()&&shade.listeners.isEmpty());old.run();ck("stale '
                                          'deadline after detach remains '
                                          'inert",shade.overlay.drawables.isEmpty()&&shade.callbacks.isEmpty());\n'
                                          '  setup();int '
                                          'original=0;if(!ShutterFeedback1941.show(nativeFlash))original++;ck("success '
                                          'bypasses native '
                                          'blink",original==0);PreviewLayout1922.rect=null;if(!ShutterFeedback1941.show(nativeFlash))original++;ck("readiness '
                                          'failure requests original native blink exactly '
                                          'once",original==1);\n'
                                          '  '
                                          'setup();ShutterFeedback1941.show(nativeFlash);old=shade.callbacks.keySet().iterator().next();shade.detach();shade.attach();ck("reattachment '
                                          'permits new '
                                          'cue",ShutterFeedback1941.show(nativeFlash));old.run();ck("old '
                                          'detached pulse cannot erase new '
                                          'cue",shade.overlay.drawables.size()==1&&shade.callbacks.size()==1&&shade.listeners.size()==1);\n'
                                          '  setup();for(int '
                                          'i=0;i<100;i++){SystemClock.now+=15;ck("rapid accepted '
                                          'retrigger '
                                          '"+i,ShutterFeedback1941.show(nativeFlash)&&shade.overlay.drawables.size()==1&&shade.callbacks.size()==1&&shade.listeners.size()==1);}old=shade.callbacks.keySet().iterator().next();SystemClock.now+=320;old.run();ck("rapid '
                                          'series releases overlay callbacks '
                                          'listener",shade.overlay.drawables.isEmpty()&&shade.callbacks.isEmpty()&&shade.listeners.isEmpty());\n'
                                          '  '
                                          'setup();ShutterFeedback1941.show(nativeFlash);shade.shown=false;frame();ck("hidden '
                                          'preview immediately clears on '
                                          'drawing",shade.overlay.drawables.isEmpty()&&shade.callbacks.isEmpty()&&shade.listeners.isEmpty());\n'
                                          '  '
                                          'setup();ShutterFeedback1941.show(nativeFlash);shade.focus=false;old=shade.callbacks.keySet().iterator().next();old.run();ck("focus '
                                          'loss releases cue on scheduled '
                                          'cleanup",shade.overlay.drawables.isEmpty()&&shade.callbacks.isEmpty()&&shade.listeners.isEmpty());\n'
                                          '  '
                                          'setup();shade.resources.metrics.density=3;ShutterFeedback1941.show(nativeFlash);c=frame();ck("frame '
                                          'follows physical dp '
                                          'density",c.ops.get(1).stroke==24&&c.ops.get(2).stroke==15);\n'
                                          '  ck("all bounds validation handles empty '
                                          'areas",!ShutterFeedback1941.valid(new '
                                          'RectF(5,5,5,30),1080,2340)&&!ShutterFeedback1941.valid(new '
                                          'RectF(-1,0,40,40),1080,2340));\n'
                                          '  '
                                          'System.out.println("HOST_FEEDBACK_ASSERTIONS="+count);System.out.println("MOCK_ANDROID_ONLY_NO_HARDWARE_OR_VISUAL_DEVICE_TEST");\n'
                                          ' }\n'
                                          '}',
 'com/hiro/ulike/PreviewLayout1922.java': 'package com.hiro.ulike;public class PreviewLayout1922 '
                                          '{public static '
                                          'com.bytedance.corecamera.ui.view.CameraShadeView '
                                          'view;public static android.graphics.RectF rect=new '
                                          'android.graphics.RectF(0,60,1080,1500);public static '
                                          'com.bytedance.corecamera.ui.view.CameraShadeView '
                                          'gestureView1925(){return view;}public static '
                                          'android.graphics.RectF viewport(){return rect;}}'}

def test(root,work,android=None):
 root=Path(root);work=Path(work);work.mkdir(parents=True,exist_ok=True)
 folder=work/'feedback-host';src=folder/'src';classes=folder/'classes'
 if folder.exists():shutil.rmtree(folder)
 src.mkdir(parents=True);classes.mkdir()
 for name,text in HOST_FILES.items():
  p=src/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(text)
 r=subprocess.run(['javac','-source','8','-target','8','-encoding','UTF-8','-d',str(classes),*[str(p) for p in src.rglob('*.java')],str(root/'ShutterFeedback1941.java')],capture_output=True,text=True)
 (folder/'compile.log').write_text(r.stdout+r.stderr);r.check_returncode()
 r=subprocess.run(['java','-cp',str(classes),'com.hiro.ulike.FeedbackTests1941'],capture_output=True,text=True)
 (work/'host-feedback1941.txt').write_text(r.stdout+r.stderr)
 print((r.stdout+r.stderr)[-1800:]);r.check_returncode()
 count=int(re.search(r'HOST_FEEDBACK_ASSERTIONS=(\d+)',r.stdout)[1])
 result={'suite':'accepted_photo_feedback','status':'passed','passed':True,'assertions':count,'device_tested':False,'pulse_ms':320,'scope':'accepted-photo drawable only'}
 (work/'host-feedback1941.json').write_text(json.dumps(result,indent=2)+'\n')
 return result

if __name__=='__main__':
 import argparse
 p=argparse.ArgumentParser();p.add_argument('--work',type=Path,required=True);args=p.parse_args()
 print(json.dumps(test(Path(__file__).resolve().parent,args.work),indent=2))
