import java.nio.file.*;import java.util.*;import java.security.*;
import com.android.tools.smali.dexlib2.*;import com.android.tools.smali.dexlib2.iface.*;import com.android.tools.smali.dexlib2.iface.instruction.*;import com.android.tools.smali.dexlib2.iface.reference.*;import com.android.tools.smali.dexlib2.immutable.*;import com.android.tools.smali.dexlib2.builder.*;import com.android.tools.smali.dexlib2.formatter.*;import app.hiro.ulike.patches.MethodContract;
public final class CallbackDexReview182{
 static void ok(boolean b,String s){if(!b)throw new AssertionError(s);}static Map<String,Method> methods(String path)throws Exception{Map<String,Method> ms=new HashMap<>();var c=DexFileFactory.loadDexContainer(Path.of(path).toFile(),Opcodes.forApi(26));for(String n:c.getDexEntryNames())for(ClassDef cl:c.getEntry(n).getDexFile().getClasses())for(Method m:cl.getMethods())ok(ms.put(DexFormatter.INSTANCE.getMethodDescriptor(m),m)==null,"duplicate method");return ms;}
 public static void main(String[]args)throws Exception{
  String raw=HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(Path.of(args[0]))));ok(raw.equals("f51c64cc2ffedf2110f18816831e5c7cff5652980b42d6bb22a4a3f37316730d"),"baseAPKpin");var stock=methods(args[0]);var delta=methods(args[1]);String key="Lcom/ss/android/medialib/RecordInvoker;->onNativeCallback_Init(I)V";ok(delta.size()==1&&delta.containsKey(key),"exactonecallbackpayload");Method old=stock.get(key),next=delta.get(key);ok(old.getAccessFlags()==2&&next.getAccessFlags()==2,"privatecallbackretained");ok(MethodContract.sha256(old).equals("9293eb56a7330b0d64008948b5710f0c088334878ed7a874d06667724883eff5"),"callbackpin");
  var body=new MutableMethodImplementation(next.getImplementation());var first=body.getInstructions().get(0);ok(first.getOpcode()==Opcode.INVOKE_STATIC_RANGE,"firsthook");ok(((RegisterRangeInstruction)first).getStartRegister()==4&&((RegisterRangeInstruction)first).getRegisterCount()==2,"receiverstatusregisters");ok(((ReferenceInstruction)first).getReference().toString().equals("Lcom/hiro/ulike/composer/NativeComposerHooks;->initCallback(Ljava/lang/Object;I)V"),"exactobserver");body.removeInstruction(0);Method restored=new ImmutableMethod(next.getDefiningClass(),next.getName(),next.getParameters(),next.getReturnType(),next.getAccessFlags(),next.getAnnotations(),next.getHiddenApiRestrictions(),body);ok(MethodContract.sha256(restored).equals(MethodContract.sha256(old)),"originalcontrolflowhandlersrestored");
  var instructions=new ArrayList<Instruction>();old.getImplementation().getInstructions().forEach(instructions::add);ok(instructions.size()==29&&instructions.get(2).getOpcode()==Opcode.IF_GEZ&&((OneRegisterInstruction)instructions.get(2)).getRegisterA()==5,"actualnonnegativebranch");
  Method init=stock.get("Lcom/ss/android/medialib/RecordInvoker;->initBeautyPlay(IILjava/lang/String;IILjava/lang/String;IZZZ)I");ok(MethodContract.sha256(init).equals("8dc53066a33d64e75cd562ebbaae682d5831f482d020a5f011a8f898a897c95e"),"terminalinitpin");int index=0,handle=-1,nativeCall=-1;for(Instruction i:init.getImplementation().getInstructions()){if(i instanceof ReferenceInstruction r){String ref=r.getReference().toString();if(i.getOpcode()==Opcode.IPUT_WIDE&&ref.equals("Lcom/ss/android/medialib/RecordInvoker;->mHandler:J"))handle=index;if(r.getReference() instanceof MethodReference m&&m.getName().equals("nativeInitBeautyPlay"))nativeCall=index;}index++;}ok(handle==3&&nativeCall==26,"nativehandlefieldassignedbeforeinit");
  System.out.println("PASS CallbackDexReview182: pinned original APK/callback/terminalinit; exact2argument observer at entry; removal restores complete original; Java status >=0 only; no render/restoration proof");
 }
}
