import java.nio.file.*;import java.util.*;
import com.android.tools.smali.dexlib2.*;import com.android.tools.smali.dexlib2.iface.*;import com.android.tools.smali.dexlib2.immutable.*;import com.android.tools.smali.dexlib2.immutable.reference.*;import com.android.tools.smali.dexlib2.builder.*;import com.android.tools.smali.dexlib2.builder.instruction.*;import com.android.tools.smali.dexlib2.iface.instruction.*;import com.android.tools.smali.dexlib2.iface.instruction.formats.*;import com.android.tools.smali.dexlib2.iface.reference.*;
public final class Transform179 {
 static final String SQ="Lcom/hiro/ulike/SaveQuality2;",SI="Lcom/hiro/ulike/SaveIo168;",CP="Lcom/hiro/ulike/ChromaPipeline177;",CH="Lcom/hiro/ulike/Chroma177;",BAR="Lcom/hiro/ulike/OpticalZoomUi$Bar;",ADV="Lcom/hiro/ulike/CaptureAdvanced3;";
 static ImmutableMethod copy(Method m,MethodImplementation b){return new ImmutableMethod(m.getDefiningClass(),m.getName(),m.getParameters(),m.getReturnType(),m.getAccessFlags(),m.getAnnotations(),m.getHiddenApiRestrictions(),b);}
 static ImmutableMethod named(Method m,String name,MethodImplementation b){return new ImmutableMethod(m.getDefiningClass(),name,m.getParameters(),m.getReturnType(),m.getAccessFlags(),m.getAnnotations(),m.getHiddenApiRestrictions(),b);}
 static ImmutableMethodParameter p(String t){return new ImmutableMethodParameter(t,Set.of(),null);}
 static ImmutableMethod m(String owner,String name,List<ImmutableMethodParameter> ps,String ret,int flags,MethodImplementation impl){return new ImmutableMethod(owner,name,ps,ret,flags,Set.of(),Set.of(),impl);}
 static ImmutableMethodReference mr(String o,String n,List<String> p,String r){return new ImmutableMethodReference(o,n,p,r);}
 static ImmutableFieldReference fr(String o,String n,String t){return new ImmutableFieldReference(o,n,t);}
 static boolean call(Method m,String owner,String name){if(m.getImplementation()==null)return false;for(var i:m.getImplementation().getInstructions())if(i instanceof ReferenceInstruction ri&&ri.getReference() instanceof MethodReference r&&r.getDefiningClass().equals(owner)&&r.getName().equals(name))return true;return false;}
 static MethodImplementation delegateSave(){var b=new MutableMethodImplementation(2);b.addInstruction(new BuilderInstruction35c(Opcode.INVOKE_STATIC,2,0,1,0,0,0,mr("Lcom/hiro/ulike/SaveFast179;","saveAndPublish",List.of("Landroid/graphics/Bitmap;","I"),"Ljava/lang/String;")));b.addInstruction(new BuilderInstruction11x(Opcode.MOVE_RESULT_OBJECT,0));b.addInstruction(new BuilderInstruction11x(Opcode.RETURN_OBJECT,0));return b;}
 static List<Method> patchSaveQuality(ClassDef c){List<Method> out=new ArrayList<>();Method output=null,norm=null;boolean save=false;for(Method x:c.getMethods()){
   if(x.getName().equals("outputSize"))output=x;if(x.getName().equals("normalizePhoto"))norm=x;
   if(x.getName().equals("saveAndPublish")&&x.getParameterTypes().size()==2){out.add(named(x,"saveAndPublishLegacy179",x.getImplementation()));out.add(copy(x,delegateSave()));save=true;}else out.add(x);
  }
  if(!save||output==null||norm==null)throw new IllegalStateException("SaveQuality anchors missing");
  {var b=new MutableMethodImplementation(1);b.addInstruction(new BuilderInstruction21c(Opcode.SGET_OBJECT,0,fr(SQ,"app","Landroid/content/Context;")));b.addInstruction(new BuilderInstruction11x(Opcode.RETURN_OBJECT,0));out.add(m(SQ,"app179",List.of(),"Landroid/content/Context;",9,b));}
  {var b=new MutableMethodImplementation(1);b.addInstruction(new BuilderInstruction21c(Opcode.SGET,0,fr(SQ,"fixed245","Z")));b.addInstruction(new BuilderInstruction11x(Opcode.RETURN,0));out.add(m(SQ,"fixed179",List.of(),"Z",9,b));}
  {var b=new MutableMethodImplementation(4);b.addInstruction(new BuilderInstruction3rc(Opcode.INVOKE_STATIC_RANGE,0,4,mr(SQ,"outputSize",List.of("I","I","I","Z"),"[I")));b.addInstruction(new BuilderInstruction11x(Opcode.MOVE_RESULT_OBJECT,0));b.addInstruction(new BuilderInstruction11x(Opcode.RETURN_OBJECT,0));out.add(m(SQ,"output179",List.of(p("I"),p("I"),p("I"),p("Z")),"[I",9,b));}
  {var b=new MutableMethodImplementation(3);b.addInstruction(new BuilderInstruction3rc(Opcode.INVOKE_STATIC_RANGE,0,3,mr(SQ,"normalizePhoto",List.of("Landroid/graphics/Bitmap;","I","Z"),"Landroid/graphics/Bitmap;")));b.addInstruction(new BuilderInstruction11x(Opcode.MOVE_RESULT_OBJECT,0));b.addInstruction(new BuilderInstruction11x(Opcode.RETURN_OBJECT,0));out.add(m(SQ,"normalize179",List.of(p("Landroid/graphics/Bitmap;"),p("I"),p("Z")),"Landroid/graphics/Bitmap;",9,b));}
  {var b=new MutableMethodImplementation(1);b.addInstruction(new BuilderInstruction21c(Opcode.SPUT_OBJECT,0,fr(SQ,"lastStatus","Ljava/lang/String;")));b.addInstruction(new BuilderInstruction10x(Opcode.RETURN_VOID));out.add(m(SQ,"status179",List.of(p("Ljava/lang/String;")),"V",9,b));}
  {var b=new MutableMethodImplementation(0);b.addInstruction(new BuilderInstruction35c(Opcode.INVOKE_STATIC,0,0,0,0,0,0,mr(SQ,"showSaveFailure",List.of(),"V")));b.addInstruction(new BuilderInstruction10x(Opcode.RETURN_VOID));out.add(m(SQ,"failure179",List.of(),"V",9,b));}
  return out;
 }
 static List<Method> patchSaveIo(ClassDef c){List<Method> out=new ArrayList<>();boolean ok=false;for(Method x:c.getMethods()){out.add(x);if(x.getName().equals("checkedPath")){ok=true;var b=new MutableMethodImplementation(2);b.addInstruction(new BuilderInstruction35c(Opcode.INVOKE_STATIC,2,0,1,0,0,0,mr(SI,"checkedPath",List.of("Landroid/content/ContentResolver;","Landroid/net/Uri;"),"Ljava/lang/String;")));b.addInstruction(new BuilderInstruction11x(Opcode.MOVE_RESULT_OBJECT,0));b.addInstruction(new BuilderInstruction11x(Opcode.RETURN_OBJECT,0));out.add(m(SI,"checkedPath179",List.of(p("Landroid/content/ContentResolver;"),p("Landroid/net/Uri;")),"Ljava/lang/String;",9,b));}}
  if(!ok)throw new IllegalStateException("checkedPath anchor missing");return out;}
 static List<Method> patchChroma(ClassDef c){List<Method> out=new ArrayList<>();boolean ok=false;for(Method x:c.getMethods())if(x.getName().equals("row")&&x.getParameterTypes().size()==5){var b=new MutableMethodImplementation(5);b.addInstruction(new BuilderInstruction3rc(Opcode.INVOKE_STATIC_RANGE,0,5,mr("Lcom/hiro/ulike/ChromaFast179;","row",List.of("[I","I","I","[I","I"),"V")));b.addInstruction(new BuilderInstruction10x(Opcode.RETURN_VOID));out.add(copy(x,b));ok=true;}else out.add(x);if(!ok)throw new IllegalStateException("chroma row missing");return out;}
 static MethodImplementation patchProcess(Method x){var b=new MutableMethodImplementation(x.getImplementation());int workNew=-1,workCtor=-1,array=-1;for(int i=0;i<b.getInstructions().size();i++){var z=b.getInstructions().get(i);if(z.getOpcode()==Opcode.NEW_INSTANCE&&z instanceof ReferenceInstruction ri&&ri.getReference().toString().equals("Lcom/hiro/ulike/DetailPixels$Work;"))workNew=i;if(z.getOpcode()==Opcode.INVOKE_DIRECT&&z instanceof ReferenceInstruction ri&&ri.getReference() instanceof MethodReference r&&r.getDefiningClass().equals("Lcom/hiro/ulike/DetailPixels$Work;")&&r.getName().equals("<init>"))workCtor=i;if(z.getOpcode()==Opcode.NEW_ARRAY&&z instanceof ReferenceInstruction ri&&ri.getReference().toString().equals("[I"))array=i;}
  if(workNew<0||workCtor<0||array<0)throw new IllegalStateException("scratch anchors missing");
  var ctor=(FiveRegisterInstruction)b.getInstructions().get(workCtor);int work=((OneRegisterInstruction)b.getInstructions().get(workNew)).getRegisterA(),len=ctor.getRegisterD();b.replaceInstruction(workNew,new BuilderInstruction10x(Opcode.NOP));b.replaceInstruction(workCtor,new BuilderInstruction35c(Opcode.INVOKE_STATIC,1,len,0,0,0,0,mr("Lcom/hiro/ulike/WorkPool179;","acquireWork",List.of("I"),"Lcom/hiro/ulike/DetailPixels$Work;")));b.addInstruction(workCtor+1,new BuilderInstruction11x(Opcode.MOVE_RESULT_OBJECT,work));
  if(array>workCtor)array++;var ar=(TwoRegisterInstruction)b.getInstructions().get(array);int dst=ar.getRegisterA(),alen=ar.getRegisterB();b.replaceInstruction(array,new BuilderInstruction35c(Opcode.INVOKE_STATIC,1,alen,0,0,0,0,mr("Lcom/hiro/ulike/WorkPool179;","acquireInts",List.of("I"),"[I")));b.addInstruction(array+1,new BuilderInstruction11x(Opcode.MOVE_RESULT_OBJECT,dst));return b;}
 static MethodImplementation patchBarCtor(Method x){var b=new MutableMethodImplementation(x.getImplementation());int changed48=0,statusHide=0;for(int i=0;i<b.getInstructions().size();i++){var z=b.getInstructions().get(i);
   if(z.getOpcode()==Opcode.CONST_HIGH16&&z instanceof NarrowLiteralInstruction li&&li.getNarrowLiteral()==Float.floatToIntBits(48f)){int r=((OneRegisterInstruction)z).getRegisterA();b.replaceInstruction(i,new BuilderInstruction21ih(Opcode.CONST_HIGH16,r,Float.floatToIntBits(52f)));changed48++;}
   if(z.getOpcode()==Opcode.IPUT_OBJECT&&z instanceof ReferenceInstruction ri&&ri.getReference().toString().equals(BAR+"->status:Landroid/widget/TextView;")){int view=((TwoRegisterInstruction)z).getRegisterA();b.addInstruction(i+1,new BuilderInstruction21s(Opcode.CONST_16,2,8));b.addInstruction(i+2,new BuilderInstruction35c(Opcode.INVOKE_VIRTUAL,2,view,2,0,0,0,mr("Landroid/widget/TextView;","setVisibility",List.of("I"),"V")));statusHide++;i+=2;}
  }if(changed48!=1||statusHide!=1)throw new IllegalStateException("bar UI anchors "+changed48+" "+statusHide);return b;}
 static MethodImplementation patchInstall(Method x){var b=new MutableMethodImplementation(x.getImplementation());int n=0;for(int i=0;i<b.getInstructions().size();i++){var z=b.getInstructions().get(i);if(z.getOpcode()==Opcode.CONST_HIGH16&&z instanceof NarrowLiteralInstruction li&&li.getNarrowLiteral()==Float.floatToIntBits(62f)){int r=((OneRegisterInstruction)z).getRegisterA();b.replaceInstruction(i,new BuilderInstruction21ih(Opcode.CONST_HIGH16,r,Float.floatToIntBits(52f)));n++;}}if(n!=1)throw new IllegalStateException("install height anchor "+n);return b;}
 public static void main(String[] a)throws Exception{var old=MergePayloads.classes(a[0]);var helper=MergePayloads.classes(a[1]);var all=new TreeMap<>(old);Path out=Path.of(a[2]);Files.createDirectories(out);Set<String> replaced=new TreeSet<>(),added=new TreeSet<>();
  for(var e:helper.entrySet()){String t=e.getKey();if(t.startsWith("Lcom/hiro/ulike/MacroUi168")){if(!old.containsKey(t))throw new IllegalStateException("missing old UI class "+t);all.put(t,e.getValue());replaced.add(t);}else if(t.startsWith("Lcom/hiro/ulike/SaveFast179")||t.startsWith("Lcom/hiro/ulike/WorkPool179")||t.startsWith("Lcom/hiro/ulike/ChromaFast179")){if(old.containsKey(t))throw new IllegalStateException("helper collision "+t);all.put(t,e.getValue());added.add(t);}else throw new IllegalStateException("unexpected helper "+t);}
  int sq=0,si=0,cp=0,ch=0,ctor=0,install=0,version=0;for(String t:List.of(SQ,SI,CP,CH,BAR,ADV)){ClassDef c=all.get(t);List<Method> ms=new ArrayList<>();if(t.equals(SQ)){ms=patchSaveQuality(c);sq=1;}else if(t.equals(SI)){ms=patchSaveIo(c);si=1;}else for(Method x:c.getMethods()){MethodImplementation impl=x.getImplementation();boolean changed=false;if(t.equals(CP)&&x.getName().equals("process")&&impl!=null){impl=patchProcess(x);cp++;changed=true;}if(t.equals(CH)&&x.getName().equals("row")&&impl!=null){}
    if(t.equals(BAR)&&x.getName().equals("<init>")&&x.getParameterTypes().size()==1){impl=patchBarCtor(x);ctor++;changed=true;}if(t.equals(BAR)&&x.getName().equals("installCore168")){impl=patchInstall(x);install++;changed=true;}if(t.equals(ADV)&&impl!=null){var b=new MutableMethodImplementation(impl);for(int i=0;i<b.getInstructions().size();i++){var z=b.getInstructions().get(i);if(z instanceof ReferenceInstruction ri&&ri.getReference() instanceof StringReference sr&&sr.getString().equals("ULike Capture v1.7.8\n")){int r=((OneRegisterInstruction)z).getRegisterA();b.replaceInstruction(i,z.getOpcode()==Opcode.CONST_STRING_JUMBO?new BuilderInstruction31c(Opcode.CONST_STRING_JUMBO,r,new ImmutableStringReference("ULike Capture v1.7.9\n")):new BuilderInstruction21c(Opcode.CONST_STRING,r,new ImmutableStringReference("ULike Capture v1.7.9\n")));version++;changed=true;}}if(changed)impl=b;}
    ms.add(changed?copy(x,impl):x);}if(t.equals(CH)){ms=patchChroma(c);ch=1;}all.put(t,new ImmutableClassDef(c.getType(),c.getAccessFlags(),c.getSuperclass(),c.getInterfaces(),c.getSourceFile(),c.getAnnotations(),c.getFields(),ms));}
  if(sq!=1||si!=1||cp!=1||ch!=1||ctor!=1||install!=1||version!=1)throw new IllegalStateException("patch counts bad");MergePayloads.writeDex(out.resolve("runtime.dex"),all.values());var emitted=MergePayloads.classes(out.resolve("runtime.dex").toString());
  Method sm=null;for(Method x:emitted.get(SQ).getMethods())if(x.getName().equals("saveAndPublish")){sm=x;break;}if(sm==null||!call(sm,"Lcom/hiro/ulike/SaveFast179;","saveAndPublish"))throw new IllegalStateException("save delegate missing");
  Files.writeString(out.resolve("runtime-audit179.txt"),"PASS v1.7.9: direct pending MediaStore HEIF path, single verification, parallel HEIF preparation, scratch reuse, pixel-exact chroma row helper, hidden zoom status, 52dp unclipped control row. Added helpers="+added.size()+", replaced UI classes="+replaced.size()+".\n");
 }
}
