package com.hiro.ulike;

import java.util.Arrays;
import java.util.Random;
import java.util.concurrent.CancellationException;
import java.util.concurrent.atomic.AtomicReference;

/** Known-truth tests distinguish random/coarse noise from real detail. */
public final class StrongNoise1957Test {
    private static int assertions,nativeParityCases;
    private static double flatBefore,flatAfter,coarseBefore,coarseAfter,chromaBefore,chromaAfter,textureTransfer,nlmDelta;
    private static final StrongNoise1957.Protection FREE=new StrongNoise1957.Protection(){public int budgetQ8(int x,int y){return 256;}public int detailQ8(int x,int y){return 0;}};
    private static final StrongNoise1957.Protection ZERO=new StrongNoise1957.Protection(){public int budgetQ8(int x,int y){return 0;}public int detailQ8(int x,int y){return 256;}};
    private static void check(boolean value,String why){assertions++;if(!value)throw new AssertionError(why+" [flat="+flatBefore+"->"+flatAfter+", coarse="+coarseBefore+"->"+coarseAfter+"]");}
    private static int clip(int v){return Math.max(0,Math.min(255,v));}
    private static int rgb(int r,int g,int b){return 0xff000000|clip(r)<<16|clip(g)<<8|clip(b);}
    private static int c(int p,int k){return p>>>(16-k*8)&255;}
    private static int[] constant(int w,int h,int p){int[] out=new int[w*h];Arrays.fill(out,p);return out;}
    private static int[] noisy(int[] clean,double sy,double sc,long seed){Random random=new Random(seed);int[] out=clean.clone();for(int i=0;i<out.length;i++){int y=(int)Math.round(random.nextGaussian()*sy),r=(int)Math.round(random.nextGaussian()*sc),b=(int)Math.round(random.nextGaussian()*sc);out[i]=rgb(c(clean[i],0)+y+r,c(clean[i],1)+y-(int)Math.round((.299*r+.114*b)/.587),c(clean[i],2)+y+b);}return out;}
    private static StrongNoise1957.Patches patches(final int[] image,final int w,final int h){return new StrongNoise1957.Patches(){public void read(int[] out,int x,int y,int width,int height){check(x>=0&&y>=0&&x+width<=w&&y+height<=h&&out.length>=width*height,"invalid model read");for(int row=0;row<height;row++)System.arraycopy(image,(y+row)*w+x,out,row*width,width);}};}
    private static StrongNoise1957.Model model(int[] src,int w,int h){return StrongNoise1957.prepare(patches(src,w,h),w,h,4,true);}
    private static int[] filter(int[] src,int w,int h,StrongNoise1957.Model m,StrongNoise1957.Protection p){int[] snapshot=src.clone(),out=src.clone();StrongNoise1957.processRange(src,out,w,h,0,h,0,h,0,4,true,m,p);check(Arrays.equals(src,snapshot),"source mutated");return out;}
    private static double rmse(int[] a,int[] b,int w,int x0,int y0,int x1,int y1){double sum=0;long n=0;for(int y=y0;y<y1;y++)for(int x=x0;x<x1;x++)for(int k=0;k<3;k++){double d=c(a[y*w+x],k)-c(b[y*w+x],k);sum+=d*d;n++;}return Math.sqrt(sum/n);}
    private static double chromaError(int[] a,int[] b,int w,int inset){double sum=0;long n=0;for(int y=inset;y<a.length/w-inset;y++)for(int x=inset;x<w-inset;x++){int p=a[y*w+x],q=b[y*w+x];double dr=(c(p,0)-c(p,1))-(c(q,0)-c(q,1)),db=(c(p,2)-c(p,1))-(c(q,2)-c(q,1));sum+=dr*dr+db*db;n+=2;}return Math.sqrt(sum/n);}
    private static int firstDifference(int[] a,int[] b){for(int i=0;i<a.length;i++)if(a[i]!=b[i])return i;return -1;}

    private static void constantsAndOwnership(){
        for(int[] size:new int[][]{{1,1},{2,3},{7,9},{33,35}})for(int p:new int[]{rgb(0,0,0),rgb(255,255,255),rgb(34,42,50),rgb(171,76,39)}){
            int[] src=constant(size[0],size[1],p);StrongNoise1957.Model m=model(src,size[0],size[1]);check(Arrays.equals(src,filter(src,size[0],size[1],m,FREE)),"constant modified");check(m.sigmaY(0)<.4&&m.sigmaC(0)<.4,"constant noise evidence");check(m.residentBytes()<=StrongNoise1957.modelMemoryBytes(size[0],size[1]),"resident exceeds reservation");
        }
        int w=61,h=47;int[] src=noisy(constant(w,h,rgb(45,51,59)),4,5,195701),snap=src.clone();StrongNoise1957.Model m=model(src,w,h);
        check(Arrays.equals(src,filter(src,w,h,m,ZERO)),"zero protection budget ignored");
        int[] off=src.clone();StrongNoise1957.processRange(src,off,w,h,0,h,0,h,0,0,true,m,FREE);check(Arrays.equals(src,off),"NR OFF modified image");
        for(int i=0;i<src.length;i+=11)src[i]=(i%255)<<24|(src[i]&0xffffff);m=model(src,w,h);int[] out=filter(src,w,h,m,FREE);
        for(int i=0;i<src.length;i++){if(src[i]>>>24!=255)check(out[i]==src[i],"nonopaque pixel changed");else check(out[i]>>>24==255,"opaque alpha changed");}
        check(Arrays.equals(snap,noisy(constant(w,h,rgb(45,51,59)),4,5,195701)),"determinism input source");
        int[] sentinel=new int[src.length];Arrays.fill(sentinel,0x12345678);Thread.currentThread().interrupt();boolean cancelled=false;try{StrongNoise1957.processRange(src,sentinel,w,h,0,h,0,h,0,4,true,m,FREE);}catch(CancellationException expected){cancelled=true;}finally{Thread.interrupted();}check(cancelled,"cancellation not propagated");for(int p:sentinel)check(p==0x12345678,"cancel before processing touched output");
    }
    private static void flatDark(){int w=192,h=160;int[] clean=constant(w,h,rgb(35,40,47)),src=noisy(clean,4,6,195702);StrongNoise1957.Model m=model(src,w,h);int[] out=filter(src,w,h,m,FREE);flatBefore=rmse(src,clean,w,12,12,w-12,h-12);flatAfter=rmse(out,clean,w,12,12,w-12,h-12);check(m.sigmaY(0)>.4,"dark sigma unmeasured");check(flatAfter<flatBefore*.70,"dark flat insufficient: "+flatBefore+" -> "+flatAfter);}
    private static int[] correlated(int[] clean,int w,int h){Random random=new Random(195703);int gw=(w+3)/4+1,gh=(h+3)/4+1;float[] grain=new float[gw*gh];for(int i=0;i<grain.length;i++)grain[i]=(float)random.nextGaussian()*7;int[] out=clean.clone();for(int y=0;y<h;y++)for(int x=0;x<w;x++){int gx=x/4,gy=y/4;float fx=x%4/4f,fy=y%4/4f;float a=grain[gy*gw+gx]*(1-fx)+grain[gy*gw+gx+1]*fx,b=grain[(gy+1)*gw+gx]*(1-fx)+grain[(gy+1)*gw+gx+1]*fx;int d=Math.round(a*(1-fy)+b*fy);out[y*w+x]=rgb(c(clean[y*w+x],0)+d,c(clean[y*w+x],1)+d,c(clean[y*w+x],2)+d);}return out;}
    private static void pyramidCoarse(){int w=256,h=192;int[] clean=constant(w,h,rgb(48,53,60)),src=correlated(clean,w,h);StrongNoise1957.Model m=model(src,w,h);int[] out=filter(src,w,h,m,FREE);coarseBefore=rmse(src,clean,w,16,16,w-16,h-16);coarseAfter=rmse(out,clean,w,16,16,w-16,h-16);check(m.sigmaY(1)>.4||m.sigmaY(2)>.4||m.sigmaY(3)>.4,"coarse scale noise unmeasured");check(coarseAfter<coarseBefore*.90,"coarse noise not visibly reduced: "+coarseBefore+" -> "+coarseAfter);check(m.residentBytes()>src.length,"actual half/quarter/eighth maps absent");}
    private static void chromaAndBoundary(){int w=192,h=160;int[] clean=constant(w,h,rgb(63,66,71));for(int y=0;y<h;y++)for(int x=w/2;x<w;x++)clean[y*w+x]=rgb(101,50,79);int[] src=noisy(clean,1,7,195704),out=filter(src,w,h,model(src,w,h),FREE);chromaBefore=chromaError(src,clean,w,12);chromaAfter=chromaError(out,clean,w,12);check(chromaAfter<chromaBefore*.70,"wide chroma insufficient: "+chromaBefore+" -> "+chromaAfter);double contrast=0;for(int y=12;y<h-12;y++)contrast+=c(out[y*w+w/2+2],0)-c(out[y*w+w/2-3],0);check(contrast/(h-24)>31,"colour boundary lost");}
    private static void detail(){int w=256,h=160;int[] clean=new int[w*h];for(int y=0;y<h;y++)for(int x=0;x<w;x++){int v=61+(int)Math.round(9*Math.sin(2*Math.PI*x/13)+5*Math.sin(2*Math.PI*(x+y)/21));if(x>w/2)v=64+((x%9<2||y%9<2)?24:0);if(y>h-30)v=x%20<2?21:159;clean[y*w+x]=rgb(v,v+2,v+4);}int[] cleanOut=filter(clean,w,h,model(clean,w,h),FREE);check(rmse(cleanOut,clean,w,10,10,w-10,h-40)<1.8,"clean texture altered");int[] src=noisy(clean,2,2,195705),out=filter(src,w,h,model(src,w,h),FREE);double mean=0,actual=0,n=0;for(int y=10;y<h-40;y++)for(int x=10;x<w/2-10;x++){mean+=c(clean[y*w+x],1);actual+=c(out[y*w+x],1);n++;}mean/=n;actual/=n;double covariance=0,energy=0;for(int y=10;y<h-40;y++)for(int x=10;x<w/2-10;x++){double a=c(clean[y*w+x],1)-mean;covariance+=a*(c(out[y*w+x],1)-actual);energy+=a*a;}textureTransfer=covariance/energy;check(textureTransfer>.88,"texture contrast lost: "+textureTransfer);double edge=0;for(int y=h-25;y<h-5;y++)edge+=c(out[y*w+8],1)-c(out[y*w+1],1);check(edge/20>130,"text edge blurred");}
    private static void nlmExecuted(){int w=64,h=48;int[] clean=constant(w,h,rgb(37,42,49)),src=noisy(clean,2,3,195706);float[] evidence=new float[16];Arrays.fill(evidence,3f);int[] local=new int[src.length],nlm=new int[src.length];StrongNoise1957.prepareJavaRange(src,local,w,h,0,h,4,true,evidence,0);StrongNoise1957.prepareJavaRange(src,nlm,w,h,0,h,4,true,evidence,1);long changed=0;double sum=0;for(int i=0;i<src.length;i++)if(local[i]!=nlm[i]){changed++;sum+=Math.abs((byte)(local[i]>>>16)-(byte)(nlm[i]>>>16));}nlmDelta=sum/src.length;check(changed>src.length/20,"NLM made no actual contribution");check(nlmDelta>.02,"NLM corrections do not differ");StrongNoise1957.Model m=model(src,w,h);check(m.nonlocalCandidates==24,"NLM bound wrong: "+m.nonlocalCandidates);}
    private static void coarseChromaAndSubtleEdges(){
        int w=256,h=192;int[] clean=constant(w,h,rgb(45,50,57)),grain=correlated(constant(w,h,rgb(48,48,48)),w,h),src=clean.clone();
        for(int i=0;i<src.length;i++){int d=Math.round((c(grain[i],0)-48)*.6f);src[i]=rgb(45+d,50-Math.round(d*.299f/.587f),57);}
        StrongNoise1957.Model m=model(src,w,h);int[] out=filter(src,w,h,m,FREE);double before=chromaError(src,clean,w,16),after=chromaError(out,clean,w,16);check(after<before*.93,"smooth low-amplitude colour blotches retained: "+before+" -> "+after);
        int[] edge=constant(w,h,rgb(44,47,50));for(int y=0;y<h;y++)for(int x=w/2;x<w;x++)edge[y*w+x]=rgb(54,57,60);
        int[] edgeNoise=noisy(edge,1.2,.8,195718),edgeOut=filter(edgeNoise,w,h,model(edgeNoise,w,h),FREE);double left=0,right=0,n=0;
        for(int y=16;y<h-16;y++)for(int x=w/2-12;x<w/2+12;x++){int i=y*w+x;check(c(edgeOut[i],1)>=41&&c(edgeOut[i],1)<=63,"subtle edge halo/overshoot");if(x<w/2-3){left+=c(edgeOut[i],1);n++;}else if(x>w/2+2)right+=c(edgeOut[i],1);}
        check(right/n-left/n>8.8,"subtle dark edge contrast lost");
        int[] gradient=new int[w*h];for(int y=0;y<h;y++)for(int x=0;x<w;x++){int v=35+x/12+y/24;gradient[y*w+x]=rgb(v,v+3,v+8);}int[] gradientOut=filter(gradient,w,h,model(gradient,w,h),FREE);check(rmse(gradientOut,gradient,w,16,16,w-16,h-16)<.4,"clean lighting gradient changed");
    }
    private static void stripsAndNative(){int w=83,h=111;int[] src=noisy(correlated(constant(w,h,rgb(44,51,57)),w,h),2,4,195707);StrongNoise1957.Model m=model(src,w,h);int[] expected=filter(src,w,h,m,FREE);for(int chunk:new int[]{1,7,19,32}){int[] assembled=src.clone();for(int y=0;y<h;y+=chunk){int end=Math.min(h,y+chunk),origin=Math.max(0,y-StrongNoise1957.HALO),last=Math.min(h,end+StrongNoise1957.HALO);int[] input=Arrays.copyOfRange(src,origin*w,last*w),output=input.clone();StrongNoise1957.processRange(input,output,w,last-origin,y-origin,end-origin,0,last-origin,origin,4,true,m,FREE);System.arraycopy(output,(y-origin)*w,assembled,y*w,(end-y)*w);}check(Arrays.equals(expected,assembled),"strip differs chunk="+chunk+" first="+firstDifference(expected,assembled));}
        final int[] parallel=src.clone();final AtomicReference<Throwable> failure=new AtomicReference<Throwable>();Thread[] workers=new Thread[3];for(int i=0;i<3;i++){final int begin=i*h/3,end=(i+1)*h/3;workers[i]=new Thread(new Runnable(){public void run(){try{StrongNoise1957.processRange(src,parallel,w,h,begin,end,0,h,0,4,true,m,FREE);}catch(Throwable t){failure.set(t);}}});workers[i].start();}for(Thread worker:workers)try{worker.join();}catch(InterruptedException e){throw new AssertionError(e);}check(failure.get()==null,"parallel worker failure");check(Arrays.equals(expected,parallel),"parallel output differs");
        if(StrongNoise1957.nativeAvailable())for(int k=0;k<6;k++){int nw=37+k*7,nh=39+k*9;int[] nsrc=noisy(constant(nw,nh,rgb(30+k*13,37+k*11,49+k*9)),k*.6+1,k*.8+1,195710+k);if(k==4)for(int i=0;i<nsrc.length;i+=13)nsrc[i]&=0x77ffffff;StrongNoise1957.Model nm=model(nsrc,nw,nh),jm=StrongNoise1957.prepareJava(patches(nsrc,nw,nh),nw,nh,4,true);int[] actual=filter(nsrc,nw,nh,nm,FREE),java=nsrc.clone();StrongNoise1957.processJavaRange(nsrc,java,nw,nh,0,nh,0,nh,0,4,true,jm,FREE);int max=0;for(int i=0;i<java.length;i++)for(int c=0;c<3;c++)max=Math.max(max,Math.abs(c(java[i],c)-c(actual[i],c)));check(Arrays.equals(java,actual),"native oracle mismatch "+k+" max="+max+" first="+firstDifference(java,actual));nativeParityCases++;}
    }
    public static void main(String[] args){constantsAndOwnership();flatDark();pyramidCoarse();chromaAndBoundary();detail();nlmExecuted();coarseChromaAndSubtleEdges();stripsAndNative();check(StrongNoise1957.modelMemoryBytes(4284,5712)<100L*1024*1024,"24.5MP model peak not bounded");check(StrongNoise1957.workspaceBytes(4284,128)<32L*1024*1024,"worker workspace not bounded");System.out.println("{\"status\":\"passed\",\"assertions\":"+assertions+",\"nativeAvailable\":"+StrongNoise1957.nativeAvailable()+",\"nativeParityCases\":"+nativeParityCases+",\"nativeParityPixelDifferences\":0,\"nr5_actual_image_pyramid_executed\":true,\"nr5_correlated_coarse_noise_reduced\":true,\"nr6_flat_dark_noise_reduced\":true,\"nr6_edge_texture_protection_checked\":true,\"nr7_wide_chroma_noise_reduced\":true,\"nr7_colour_boundary_protection_checked\":true,\"nr8_same_image_nlm_executed\":true,\"nr8_bounded_search_checked\":true,\"strip_invariance_alpha_ownership_checked\":true,\"metrics\":{\"flatRmseBefore\":"+flatBefore+",\"flatRmseAfter\":"+flatAfter+",\"coarseRmseBefore\":"+coarseBefore+",\"coarseRmseAfter\":"+coarseAfter+",\"chromaErrorBefore\":"+chromaBefore+",\"chromaErrorAfter\":"+chromaAfter+",\"textureContrastTransfer\":"+textureTransfer+",\"nlmCorrectionDelta\":"+nlmDelta+",\"modelPeak24MP\":"+StrongNoise1957.modelMemoryBytes(4284,5712)+"}}");}
}
