package com.hiro.ulike.binding;
import com.hiro.ulike.hdr.stillanalysis.StillMessageCollector;import com.hiro.ulike.style.SampledMakeupPipeline;import java.util.*;import java.nio.file.*;import java.security.*;
public class TextureGeometryContracts {
 static int checks;static void check(boolean b){checks++;if(!b)throw new AssertionError("check "+checks);}static void close(double a,double b){check(Math.abs(a-b)<2e-14);}interface Work{void run()throws Exception;}static void fails(Work w)throws Exception{try{w.run();}catch(Exception expected){checks++;return;}throw new AssertionError("accepted invalid sample");}
 static String sha(byte[] b)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(b));}
 static double sample(byte[] b,int w,int h,int ch,double u,double v,boolean pm){double x=Math.max(0,Math.min(w-1,u*w-.5)),y=Math.max(0,Math.min(h-1,v*h-.5));int ix=(int)Math.floor(x),iy=(int)Math.floor(y);double sum=0;for(int dy=0;dy<2;dy++)for(int dx=0;dx<2;dx++){int i=(Math.min(h-1,iy+dy)*w+Math.min(w-1,ix+dx))*4;double weight=(dx==0?1-(x-ix):x-ix)*(dy==0?1-(y-iy):y-iy);sum+=weight*(b[i+ch]&255)/255.0*(pm&&ch<3?(b[i+3]&255)/255.0:1);}return sum;}
 static void textures(Path root,Path fixtures)throws Exception{
  Random rng=new Random(417);int images=0;
  for(String line:Files.readAllLines(fixtures)){String[] f=line.split("\t");byte[] bytes=Files.readAllBytes(root.resolve(f[0]));PinnedPngTexture p=PinnedPngTexture.readPinned(bytes,f[1]);byte[] rgba=p.copyStraightRgba();check(sha(rgba).equals(f[2]));check(p.width==Integer.parseInt(f[3])&&p.height==Integer.parseInt(f[4]));double[] out=new double[4];
   for(int i=0;i<96;i++){double u=rng.nextDouble()*1.4-.2,v=rng.nextDouble()*1.4-.2;for(boolean pm:new boolean[]{false,true})for(PinnedPngTexture.Rows rows:PinnedPngTexture.Rows.values()){p.sample(u,v,rows,pm,out);for(int c=0;c<4;c++)close(out[c],sample(rgba,p.width,p.height,c,u,rows==PinnedPngTexture.Rows.FIRST_DECODED_ROW_AT_V_ONE?1-v:v,pm));}}
   byte before=rgba[0];rgba[0]^=1;check(p.copyStraightRgba()[0]==before);fails(()->p.sample(Double.NaN,0,PinnedPngTexture.Rows.FIRST_DECODED_ROW_AT_V_ZERO,true,out));byte[] corrupted=bytes.clone();corrupted[41]^=1;fails(()->PinnedPngTexture.readPinned(corrupted,f[1]));images++;
  }check(images==17);
 }
 static ObservedStyleFrame observation(Object id,double[] uv){StillMessageCollector c=new StillMessageCollector(81,ObservedStyleFrame.expectedFeatures(ShotStyleSettings.PURITY));c.submitted();for(String f:ObservedStyleFrame.expectedFeatures(ShotStyleSettings.PURITY))if(!f.equals("3dmakeup4"))packet(c,f,"END",-1,1,"0");packet(c,"3dmakeup4","mvp",0,1,"1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1");int ord=2;for(int first=0;first<1427;first+=64){int count=Math.min(64,1427-first);StringBuilder b=new StringBuilder();for(int i=first;i<first+count;i++){if(i!=first)b.append(',');b.append(uv[i*2]*2-1).append(',').append(uv[i*2+1]*2-1).append(",0");}packet(c,"3dmakeup4","vertices",0,ord++,first+","+count+",1427;"+b);}packet(c,"3dmakeup4","uniform",0,ord++,"face0,intensity,0.625");packet(c,"3dmakeup4","END",-1,ord,Integer.toString(ord-1));return ObservedStyleFrame.parse(c.finish(),id,81,ShotStyleSettings.PURITY);}
 static void packet(StillMessageCollector c,String f,String k,int face,int ord,String data){c.accept(StillMessageCollector.MESSAGE_ID,81,ord,"S1|"+f+"|"+k+"|"+face+"|"+data);}
 static void geometry(Path root)throws Exception{
  AuthoredMesh mesh=AuthoredMesh.readPinned(Files.readAllBytes(root.resolve("purity/3dmakeup4/mesh/Mesh1200wan.mesh")),"ff70ea10d239851697a6f9f0f48d25d1be0e9534d32fc4aa4d7abda551d5d0c0");PinnedPngTexture texture=PinnedPngTexture.readPinned(Files.readAllBytes(root.resolve("purity/3dmakeup4/image/makeup3d_open.png")),"f91dbf4cc446b0db5d3af7eb6a314f0d706c087543357751011e2a04f48a5f47");
  Object id=new Object();ObservedStyleFrame frame=observation(id,mesh.copyUv());SampledMakeupPipeline.FrameTile tile=new SampledMakeupPipeline.FrameTile("synthetic-geometry",81,127,91,0,0,127,91);Purity3dBinding.ShaderBase base=new Purity3dBinding.ShaderBase(){public Object frameIdentity(){return id;}public void sample(double u,double v,double[] out){out[0]=u;out[1]=v;out[2]=.5;}};
  SampledMakeupPipeline.ResolvedPass p=Purity3dBinding.resolve(frame,id,tile,0,"face0",mesh,texture,PinnedPngTexture.Rows.FIRST_DECODED_ROW_AT_V_ZERO,base,Purity3dBinding.RasterPolicy.OPENGL_CLIP_TO_TOP_LEFT_NO_CULL_NO_DEPTH_LAST_TRIANGLE_SINGLE_CENTER);
  int covered=0;double[] actual=new double[4],dst=new double[tile.pixels()*3];Arrays.fill(dst,.8);
  double[] result=SampledMakeupPipeline.apply(SampledMakeupPipeline.Domain.ENCODED_SDR_FULL_RANGE,tile,dst,p);
  for(int y=0;y<tile.height;y++)for(int x=0;x<tile.width;x++){int i=y*tile.width+x;check(p.coverage[i]==0||p.coverage[i]==1);if(p.coverage[i]==0){for(int c=0;c<3;c++)check(result[i*3+c]==.8);continue;}covered++;double u=(x+.5)/tile.width,v=1-(y+.5)/tile.height;close(p.shaderBaseRgb[i*3],u);close(p.shaderBaseRgb[i*3+1],v);texture.sample(u,v+.085,PinnedPngTexture.Rows.FIRST_DECODED_ROW_AT_V_ZERO,true,actual);for(int ch=0;ch<4;ch++)close(p.rgba[i*4+ch],actual[ch]);for(int ch=0;ch<3;ch++){double b=p.shaderBaseRgb[i*3+ch],alpha=actual[3];close(result[i*3+ch],b*(1-alpha*.625)+b*actual[ch]*.625);}}
  check(covered>1000);fails(()->Purity3dBinding.resolve(frame,new Object(),tile,0,"face0",mesh,texture,PinnedPngTexture.Rows.FIRST_DECODED_ROW_AT_V_ZERO,base,Purity3dBinding.RasterPolicy.OPENGL_CLIP_TO_TOP_LEFT_NO_CULL_NO_DEPTH_LAST_TRIANGLE_SINGLE_CENTER));check(!frame.completeStyleBinding);System.out.println("3D synthetic planar geometry covered="+covered+"; live device geometry not verified");
 }
 public static void main(String[] args)throws Exception{textures(Path.of(args[0]),Path.of(args[1]));geometry(Path.of(args[0]));System.out.println("Texture/geometry contracts PASS "+checks);}
}
