package com.hiro.ulike;
import android.os.*;import android.view.*;import android.graphics.*;import android.hardware.camera2.*;
import com.ss.android.vesdk.*;import com.ss.android.vesdk.frame.*;import java.util.*;import java.lang.ref.*;
import i.s.a.w.l0.c;import i.s.a.w.m;import i.s.a.w.w;
public class AuditTest1929 {
 static int checks;static VECameraCapture capture;static Mode mode;static OpticalZoom.Route route;
 static void ck(boolean b,String why){checks++;if(!b)throw new AssertionError(why);}
 public static class Camera{public c manager=new c();public c U(){return manager;}}
 public static class Mode{public Camera g=new Camera();public Handler k=new Handler();}
 public static class Provider{public Object d,a=new Object(),j=new Object(),k=new Object();public boolean h,e=true;public m.d b=m.d.PIXEL_FORMAT_OpenGL_OES;public SurfaceTexture texture=new SurfaceTexture();public Surface surface=new Surface();public int detached;public Provider(Object camera){d=camera;}public SurfaceTexture f(){return texture;}public Surface d(){return surface;}public void p(){if(texture!=null)texture.release();}public void o(){detached++;a=j;if(surface!=null)surface.release();}}
 public static class Server{public c mProviderManager=new c();public Object mSurfaceTextureLock=new Object();public boolean mbNeedReleaseSurfaceTexture=true;}
 public static class Callback{public OpticalZoom.Route r;public long token;public CameraCaptureSession.StateCallback next;Callback(OpticalZoom.Route r,long token,CameraCaptureSession.StateCallback cb){this.r=r;this.token=token;next=cb;}}
 static void reset(){ManualLens170.reset();OpticalZoom.MAIN=new Handler();OpticalZoom.failures=0;ExitBusy1921.busy=false;SystemClock.now=100;Build.VERSION.SDK_INT=36;capture=new VECameraCapture();mode=new Mode();route=new OpticalZoom.Route(mode);ManualLens170.f.put("capture",new WeakReference<Object>(capture));ManualLens170.f.put("active",route);ManualLens170.f.put("epoch",7L);ManualLens170.f.put("foreground",true);ManualLens170.f.put("recording",false);ManualLens170.f.put("lastFrame",1000L);ManualLens170.f.put("LOCK",new Object());ManualLens170.f.put("rejected",new HashSet<String>(Arrays.asList("old")));ManualLens170.setup(route,1);}
 static Provider provider(){Provider p=new Provider(mode.g);mode.g.manager.a=p;return p;}
 static TECapturePipeline pipe(){TECapturePipeline p=new TECapturePipeline();p.texture=new SurfaceTexture();capture.n.list.add(p);return p;}
 static c.a setting(){c.a s=new c.a();s.a=true;s.i=true;s.b=new w(1920,1080);s.c=new i.s.a.w.l0.b.c(){};s.d=new SurfaceTexture();s.e=1;s.f=2;s.g=new Surface();s.h=m.d.PIXEL_FORMAT_OpenGL_OES;return s;}
 static void copies(){
  c.a s=setting(),t=new c.a();ProviderLifecycle1929.copy(t,s);ck(ProviderLifecycle1929.same(s,t),"complete copy matches");ck(s.b!=t.b,"mutable size frozen");ck(t.g==s.g&&t.h==s.h&&t.i==s.i,"format Surface primary copied");s.b.c++;ck(!ProviderLifecycle1929.same(s,t),"in-place dimensions invalidate cache");
  for(int field=0;field<10;field++){s=setting();t=new c.a();ProviderLifecycle1929.copy(t,s);switch(field){case 0:s.a=false;break;case 1:s.b.c++;break;case 2:s.b.j++;break;case 3:s.c=new i.s.a.w.l0.b.c(){};break;case 4:s.d=new SurfaceTexture();break;case 5:s.e++;break;case 6:s.f++;break;case 7:s.g=new Surface();break;case 8:s.h=m.d.PIXEL_FORMAT_Recorder;break;case 9:s.i=false;break;}ck(!ProviderLifecycle1929.same(s,t),"every identity component "+field);ProviderLifecycle1929.copy(t,s);ck(ProviderLifecycle1929.same(s,t),"changed component copied "+field);}
  s=setting();s.b=null;ProviderLifecycle1929.copy(t,s);ck(t.b==null&&!ProviderLifecycle1929.same(t,s),"invalid size never reusable");ck(!ProviderLifecycle1929.same(null,t)&&!ProviderLifecycle1929.same(t,new Object()),"null foreign identity");
 }
 static void reuse(){
  for(int bad=0;bad<7;bad++){reset();Provider p=provider();if(bad==1)mode.g.manager.a=null;if(bad==2)p.d=new Camera();if(bad==3)p.h=true;if(bad==4)p.surface.valid=false;if(bad==5)p.texture.released=true;if(bad==6)p.surface=null;ck((ProviderLifecycle1929.liveManager(mode.g)!=null)==(bad==0||bad==3),"reuse actual native provider "+bad);}
  reset();Provider p=provider();p.texture=null;ck(ProviderLifecycle1929.liveManager(mode.g)==mode.g.manager,"valid external Surface remains supported");p.b=m.d.PIXEL_FORMAT_YUV420;p.surface=null;ck(ProviderLifecycle1929.liveManager(mode.g)==mode.g.manager,"buffer allocation remains native");ck(ProviderLifecycle1929.liveManager(new Object())==null,"missing native method safely not reusable");
 }
 static void release(){
  for(int swap=0;swap<4;swap++)for(boolean need:new boolean[]{false,true}){
   reset();Server server=new Server();c oldManager=server.mProviderManager;Provider old=new Provider(mode.g);oldManager.a=old;server.mbNeedReleaseSurfaceTexture=need;Object task=new Object();ProviderLifecycle1929.captureRelease(task,server);Provider fresh=new Provider(new Camera());
   if(swap==1){server.mProviderManager=new c();server.mProviderManager.a=fresh;}
   if(swap==2)server.mProviderManager.a=fresh;
   if(swap==3){server.mProviderManager=new c();server.mProviderManager.a=old;}
   ProviderLifecycle1929.release(task,server);ck(old.detached==(swap==3?0:1),"only captured provider detached "+swap);ck(old.texture.releases==(need&&swap!=3?1:0),"texture release belongs to captured intent "+swap);ck(fresh.detached==0&&fresh.texture.releases==0,"new provider unaffected "+swap);
   if(swap==0)ck(server.mProviderManager.a==null&&!server.mbNeedReleaseSurfaceTexture,"current cleanup state");else ck(server.mbNeedReleaseSurfaceTexture==need,"new-generation release intent retained");
   int count=old.detached;ProviderLifecycle1929.release(task,server);ck(old.detached==count,"duplicate task idempotent");
  }
  reset();Server s=new Server();Provider old=new Provider(mode.g);s.mProviderManager.a=old;Object task=new Object();ProviderLifecycle1929.captureRelease(task,s);Provider fresh=new Provider(new Camera());fresh.texture=old.texture;s.mProviderManager=new c();s.mProviderManager.a=fresh;ProviderLifecycle1929.release(task,s);ck(old.texture.releases==0&&old.detached==1&&fresh.detached==0,"shared texture new Surface protects renderer");
  reset();s=new Server();old=new Provider(mode.g);s.mProviderManager.a=old;task=new Object();ProviderLifecycle1929.captureRelease(task,s);fresh=new Provider(new Camera());fresh.surface=old.surface;fresh.texture=old.texture;s.mProviderManager=new c();s.mProviderManager.a=fresh;ProviderLifecycle1929.release(task,s);ck(fresh.surface.releases==0&&fresh.texture.releases==0,"adopted exact Surface not released");
  reset();s=new Server();fresh=new Provider(mode.g);s.mProviderManager.a=fresh;ProviderLifecycle1929.release(new Object(),s);ck(fresh.detached==0,"missing ticket never falls back to mutable global manager");
 }
 static void inputs()throws Exception{
  for(int state=0;state<8;state++){reset();TECapturePipeline p=pipe();if(state==1)capture.n=null;if(state==2)capture.n.list.clear();if(state==3)p.valid=false;if(state==4)p.preview=false;if(state==5)p.texture=null;if(state==6){p.texture=null;p.surface=new Surface();p.surface.valid=false;}if(state==7){p.texture=null;p.surface=new Surface();}ck(PreviewInputs1929.before(capture)==(state==0||state==7),"real input readiness "+state);ck(capture.renewals==0,"valid or missing inputs not fabricated "+state);}
  reset();TECapturePipeline p=pipe();p.texture.released=true;ck(PreviewInputs1929.sourcesReady(capture)&&capture.renewals==0,"readiness probe does not renew GL target");ck(PreviewInputs1929.before(capture)&&capture.renewals==1,"native renewal requested for released texture only");
  for(int mask=0;mask<8;mask++){reset();p=pipe();p.texture.released=true;if((mask&1)!=0)capture.p.set(false);if((mask&2)!=0)ManualLens170.f.put("recording",true);if((mask&4)!=0)ExitBusy1921.busy=true;ck(PreviewInputs1929.before(capture)==(mask==0),"renew protection "+mask);ck(capture.renewals==(mask==0?1:0),"no renewal while busy "+mask);}
  for(int state=0;state<5;state++){reset();p=pipe();p.format=m.d.PIXEL_FORMAT_Recorder;p.recorder=new Surface();if(state==1)p.recorder=null;if(state==2)p.recorder.valid=false;if(state==3)p.texture.released=true;if(state==4)p.texture=null;ck(PreviewInputs1929.before(capture)==(state==0||state==4),"recorder real Surface readiness "+state);}
  for(int state=0;state<5;state++){reset();pipe().texture.released=true;if(state==0)route.rear=false;if(state==1)route.failed=true;if(state==2)ManualLens170.f.put("foreground",false);if(state==3)ManualLens170.f.put("capture",new WeakReference<Object>(new Object()));if(state==4)ManualLens170.f.put("epoch",8L);ck(PreviewInputs1929.before(capture)&&capture.renewals==0,"non-current-rear native semantics preserved "+state);}
  reset();p=pipe();p.format=m.d.PIXEL_FORMAT_YUV420;p.texture=null;ck(PreviewInputs1929.before(capture),"buffer image allocation is native");ck(PreviewInputs1929.before(null),"null native original semantics preserved");
 }
 static void foreground()throws Exception{
  for(int state=0;state<4;state++){reset();ManualLens170.f.put("foreground",false);ManualLens170.f.put("attempt",2);Object caller=capture;if(state==1)ManualLens170.f.put("foreground",true);if(state==2)caller=new VECameraCapture();if(state==3)ManualLens170.f.put("capture",new WeakReference<Object>(null));PreviewInputs1929.foreground(caller);ck(ManualLens170.number("epoch")==7&&ManualLens170.get("active")==route,"opened route generation never invalidated "+state);ck(ManualLens170.number("attempt")== (state==0?0:2),"recovery rearm only foreground transition "+state);ck(((Set<?>)ManualLens170.get("rejected")).isEmpty()==(state==0),"rejected lens cache rearmed "+state);}
 }
 static void pixels()throws Exception{
  reset();Provider p=provider();ck(PreviewInputs1929.deliveredTime()==0,"capture metadata without image is not visible preview");PreviewInputs1929.pixel(p,new Object());ck(PreviewInputs1929.deliveredTime()==100,"actual image delivery establishes preview");SystemClock.now=200;PreviewInputs1929.pixel(p,new Object());ck(PreviewInputs1929.deliveredTime()==200,"live image delivery updates timestamp");mode.g.manager.a=new Provider(mode.g);SystemClock.now=300;PreviewInputs1929.pixel(p,new Object());ck(PreviewInputs1929.deliveredTime()==0,"replaced provider cannot keep new preview alive");
  for(int bad=0;bad<10;bad++){reset();p=provider();if(bad==0)p.d=new Camera();if(bad==1)p.h=true;if(bad==2)p.e=false;if(bad==3)p.a=null;if(bad==4)p.a=p.j;if(bad==5)p.a=p.k;if(bad==6)ManualLens170.f.put("foreground",false);if(bad==7)route.failed=true;if(bad==8)ManualLens170.f.put("epoch",8L);if(bad==9)mode.g.manager.a=new Provider(mode.g);PreviewInputs1929.pixel(p,new Object());ck(PreviewInputs1929.deliveredTime()==0,"stale/stopped/nonpreview/dummy image rejected "+bad);}
  reset();p=provider();p.texture=null;ck(PreviewInputs1929.deliveredTime()==1000,"Surface-only pipeline has no image callback; no false restart");p.texture=new SurfaceTexture();p.b=m.d.PIXEL_FORMAT_YUV420;ck(PreviewInputs1929.deliveredTime()==1000,"nontexture native monitoring unchanged");route.rear=false;ck(PreviewInputs1929.deliveredTime()==1000,"front monitoring unchanged");
  reset();p=provider();PreviewInputs1929.pixel(p,new Object());ManualLens170.f.put("lastFrame",50L);ck(PreviewInputs1929.deliveredTime()==50,"both metadata and pixels must be recent");SystemClock.now=300;p.h=true;PreviewInputs1929.pixel(p,new Object());ManualLens170.f.put("lastFrame",1000L);ck(PreviewInputs1929.deliveredTime()==100,"stopped cached provider cannot refresh heartbeat");
 }
 static void fallback()throws Exception{
  reset();CameraCaptureSession old=new CameraCaptureSession(),replacement=new CameraCaptureSession();ManualLens170.pin(old,route);Callback cb=new Callback(route,1,new CameraCaptureSession.StateCallback(){public void onConfigureFailed(CameraCaptureSession s){ck(!route.failed,"nested native fallback sees live route");ManualLens170.setup(route,2);ManualLens170.pin(replacement,route);route.configured=true;}});SessionFallback1929.failed(cb,old);mode.k.drain();ck(!route.failed&&route.configured&&old.closes==1&&replacement.closes==0,"supported fallback is preserved; only rejected session closed");ck(((WeakReference<?>)ManualLens170.session(route)).get()==replacement,"replacement session tracking retained");
  reset();old=new CameraCaptureSession();cb=new Callback(route,1,null);SessionFallback1929.failed(cb,old);ck(!route.failed&&mode.k.tasks.size()==1,"failure deferred one native queue turn");mode.k.drain();ck(route.failed&&OpticalZoom.failures==1,"unsupported configuration ends with bounded existing recovery");
  reset();old=new CameraCaptureSession();cb=new Callback(route,1,new CameraCaptureSession.StateCallback(){public void onConfigureFailed(CameraCaptureSession s){mode.k.post(new Runnable(){public void run(){ManualLens170.setup(route,2);route.configured=true;}});}});SessionFallback1929.failed(cb,old);mode.k.drain();ck(!route.failed&&route.configured,"asynchronous native fallback precedes failure handling");
  for(int stale=0;stale<5;stale++){reset();old=new CameraCaptureSession();final int[]calls={0};cb=new Callback(route,1,new CameraCaptureSession.StateCallback(){public void onConfigureFailed(CameraCaptureSession s){calls[0]++;}});if(stale==0)ManualLens170.setup(route,2);if(stale==1)ManualLens170.f.put("epoch",8L);if(stale==2)ManualLens170.f.put("foreground",false);if(stale==3)ManualLens170.f.put("active",new OpticalZoom.Route(mode));if(stale==4)cb.r=null;SessionFallback1929.failed(cb,old);mode.k.drain();ck(calls[0]==0&&!route.failed&&old.closes==1,"stale failure is not forwarded "+stale);}
  for(int stale=0;stale<4;stale++){reset();old=new CameraCaptureSession();cb=new Callback(route,1,null);SessionFallback1929.failed(cb,old);if(stale==0)ManualLens170.setup(route,2);if(stale==1)ManualLens170.f.put("epoch",8L);if(stale==2)ManualLens170.f.put("foreground",false);if(stale==3)ManualLens170.f.put("active",new OpticalZoom.Route(mode));mode.k.drain();ck(!route.failed,"queued failure rechecks generation "+stale);}
  reset();old=new CameraCaptureSession();cb=new Callback(route,1,new CameraCaptureSession.StateCallback(){public void onConfigureFailed(CameraCaptureSession s){throw new IllegalStateException("native");}});SessionFallback1929.failed(cb,old);mode.k.drain();ck(route.failed&&old.closes==1,"native callback exception is contained");
 }
 public static void main(String[]args)throws Exception{copies();reuse();release();inputs();foreground();pixels();fallback();System.out.println("PASS1929 shipped helper assertions="+checks);}
}
