package com.hiro.ulike;
import android.graphics.RectF;import android.widget.RelativeLayout.LayoutParams;import com.bytedance.corecamera.ui.view.*;import com.bytedance.corecamera.camera.basic.PureCameraFragment;import java.lang.reflect.*;
public class GeometryHost1937 {
 static int checks; static void ok(boolean b,String why){checks++;if(!b)throw new AssertionError(why);}
 static class Supplier implements i.f.l.n.n {}
 static class Capture implements com.ss.android.vesdk.camera.ICameraCapture {}
 static PureCameraFragment owner(CameraShadeView shade){PureCameraFragment f=new PureCameraFragment();f.o=new android.view.ViewGroup();f.r=1;f.y=new i.f.l.n.q.y.c();f.y.s=new CameraView();f.y.s.shade=shade;f.y.g=new android.view.SurfaceView();f.y.r=new i.f.l.j();f.y.r.a=new i.f.l.h();f.y.r.scene=new i.f.l.u.g();f.y.r.scene.property=new i.f.l.u.p<Object>();f.y.r.a.p=new PreviewView();f.y.r.a.b=new Supplier();f.y.r.a.e=new com.ss.android.vesdk.VERecorder();f.y.r.a.e.render=new com.ss.android.vesdk.render.VERenderView();f.y.r.a.e.capture=new Capture();return f;}
 static void delivered(PureCameraFragment f,RectF r){LayoutGeometry1937.beginDelivery(f,r);LayoutGeometry1937.markDelivery(f,r);}
 public static void main(String[] args)throws Exception {
  CameraShadeView s=new CameraShadeView();PreviewLayout1922.active=s;
  i.o.a.b1.a.g.y api=new i.o.a.b1.a.g.y();i.o.a.b1.a.d.b bg=new i.o.a.b1.a.d.b();bg.b=s;bg.d=api;api.e=bg;i.o.a.m.j.f legacy=new i.o.a.m.j.f();legacy.a=s;
  for(int[] dims:new int[][]{{742,1536},{600,1200},{1200,1600},{1080,2340},{1536,742},{720,1536},{720,1500}}){s.width=dims[0];s.height=dims[1];ok(LayoutGeometry1937.cameraWidth(api)==dims[0],"camera local width");ok(LayoutGeometry1937.cameraHeight(api)==dims[1],"camera local height");ok(LayoutGeometry1937.previewWidth(legacy)==dims[0],"legacy local width");ok(LayoutGeometry1937.previewHeight(legacy)==dims[1],"legacy local height");}
  s.width=742;s.height=1536;s.attached=false;ok(LayoutGeometry1937.cameraWidth(api)==1080,"detached native width");ok(LayoutGeometry1937.cameraHeight(api)==2340,"detached native height");s.attached=true;s.width=0;ok(LayoutGeometry1937.cameraWidth(api)==1080,"zero native width");ok(LayoutGeometry1937.previewHeight(legacy)==2340,"zero dimension pair fallback");s.width=742;bg.d=new i.o.a.b1.a.g.y();ok(LayoutGeometry1937.cameraWidth(api)==1080,"wrong API owner");bg.d=api;PreviewLayout1922.active=new CameraShadeView();ok(LayoutGeometry1937.cameraWidth(api)==1080,"old shade native width");PreviewLayout1922.active=s;ok(LayoutGeometry1937.previewWidth(null)==1080,"null fallback");ok(LayoutGeometry1937.cameraHeight(null)==2340,"null height fallback");
  ok(i.n.c.a.o.w.e.p()!=LayoutGeometry1937.cameraWidth(api),"native baseline stale screen-width mismatch reproduced");
  PureCameraFragment f=owner(s);LayoutParams p=new LayoutParams(-1,1536),q=new LayoutParams(-1,1536);RectF normal=new RectF(0,131,742,1120),bad=new RectF(0,309,742,1120);
  ok(f.M2(p,q),"native baseline ignores changed displayRect with identical LP");
  ok(!LayoutGeometry1937.equivalent(f,p,q,normal),"first equal LP still dispatches");
  delivered(f,normal);ok(LayoutGeometry1937.equivalent(f,p,q,normal),"unchanged geometry fast path");ok(!LayoutGeometry1937.equivalent(f,p,q,bad),"equal LP changed rect dispatches");
  delivered(f,bad);ok(!LayoutGeometry1937.equivalent(f,p,q,normal),"restored 3:4 rect dispatches");delivered(f,normal);
  RectF alias=new RectF(normal);delivered(f,alias);alias.top=309;ok(!LayoutGeometry1937.equivalent(f,p,q,alias),"immutable rect snapshot");ok(LayoutGeometry1937.equivalent(f,p,q,normal),"mutated caller object cannot rewrite snapshot");
  q.topMargin=1;ok(!LayoutGeometry1937.equivalent(f,p,q,normal),"changed native LP dispatches");q.topMargin=0;
  s.width=720;ok(!LayoutGeometry1937.equivalent(f,p,q,normal),"same LP measured resize dispatches");s.width=742;
  s.epoch++;ok(!LayoutGeometry1937.equivalent(f,p,q,normal),"same view new generation dispatches");delivered(f,normal);
  f.y.r.a.e.render=new com.ss.android.vesdk.render.VERenderView();ok(!LayoutGeometry1937.equivalent(f,p,q,normal),"same view new renderer dispatches");delivered(f,normal);
  f.y.r.a.e.capture=new Capture();ok(!LayoutGeometry1937.equivalent(f,p,q,normal),"new capture dispatches");delivered(f,normal);
  f.y.g=new android.view.SurfaceView();ok(!LayoutGeometry1937.equivalent(f,p,q,normal),"new SurfaceView dispatches");delivered(f,normal);
  f.o=new android.view.ViewGroup();ok(!LayoutGeometry1937.equivalent(f,p,q,normal),"new native container dispatches");delivered(f,normal);
  f.y.r.a.e=new com.ss.android.vesdk.VERecorder();ok(!LayoutGeometry1937.equivalent(f,p,q,normal),"new recorder dispatches");delivered(f,normal);ok(LayoutGeometry1937.equivalent(f,p,q,normal),"null render/capture supports native SurfaceView route");
  LayoutGeometry1937.beginDelivery(f,bad);ok(!LayoutGeometry1937.equivalent(f,p,q,normal),"throwing delivery cannot preserve old success cache");ok(!LayoutGeometry1937.equivalent(f,p,q,bad),"uncompleted delivery not cached");
  LayoutGeometry1937.beginDelivery(f,normal);f.y.r.a.e=new com.ss.android.vesdk.VERecorder();LayoutGeometry1937.markDelivery(f,normal);ok(!LayoutGeometry1937.equivalent(f,p,q,normal),"callback changes renderer during delivery not cached");
  delivered(f,normal);ok(LayoutGeometry1937.equivalent(f,p,q,normal),"new session completed delivery cached");
  LayoutGeometry1937.beginDelivery(f,normal);s.epoch++;LayoutGeometry1937.markDelivery(f,normal);ok(!LayoutGeometry1937.equivalent(f,p,q,normal),"generation changes during delivery not cached");
  f.y.r.a.e=null;delivered(f,normal);ok(!LayoutGeometry1937.equivalent(f,p,q,normal),"missing recorder never cached");
  s.attached=false;ok(LayoutGeometry1937.equivalent(f,p,q,normal),"detached owner preserves native duplicate policy");s.attached=true;
  PureCameraFragment other=owner(new CameraShadeView());ok(LayoutGeometry1937.equivalent(other,p,q,normal),"old controller cannot borrow active shade");
  f.y.r.a.e=new com.ss.android.vesdk.VERecorder();RectF invalid=new RectF(0,Float.NaN,742,1120);delivered(f,invalid);ok(!LayoutGeometry1937.equivalent(f,p,q,normal),"nonfinite rect not cached");
  
  PureCameraFragment ready=owner(s);i.f.l.u.g scene=ready.y.r.scene;ready.y.r.scene=null;delivered(ready,normal);ok(!LayoutGeometry1937.equivalent(ready,p,q,normal),"void o0 without scene must not cache");ready.y.r.scene=scene;ok(!LayoutGeometry1937.equivalent(ready,p,q,normal),"registered scene requires first actual delivery");delivered(ready,normal);ok(LayoutGeometry1937.equivalent(ready,p,q,normal),"ready scene fast path");
  scene.property=null;delivered(ready,normal);ok(!LayoutGeometry1937.equivalent(ready,p,q,normal),"void o0 without property must not cache");scene.property=new i.f.l.u.p<Object>();delivered(ready,normal);ok(LayoutGeometry1937.equivalent(ready,p,q,normal),"ready property fast path");
  PreviewView preview=ready.y.r.a.p;ready.y.r.a.p=null;delivered(ready,normal);ok(!LayoutGeometry1937.equivalent(ready,p,q,normal),"manager E null preview does not count as delivery");ready.y.r.a.p=preview;preview.height=0;delivered(ready,normal);ok(!LayoutGeometry1937.equivalent(ready,p,q,normal),"zero height preview not cached");preview.height=1536;preview.width=0;delivered(ready,normal);ok(!LayoutGeometry1937.equivalent(ready,p,q,normal),"zero width preview not cached");preview.width=742;ready.y.r.a.s=true;delivered(ready,normal);ok(!LayoutGeometry1937.equivalent(ready,p,q,normal),"queued surface post not counted completed");ready.y.r.a.s=false;ok(!LayoutGeometry1937.equivalent(ready,p,q,normal),"unblocked preview still needs first completed delivery");delivered(ready,normal);ok(LayoutGeometry1937.equivalent(ready,p,q,normal),"ready unqueued preview fast path");
  ready.y.r.a.b=null;delivered(ready,normal);ok(!LayoutGeometry1937.equivalent(ready,p,q,normal),"missing supplier not cached");ready.y.r.a.b=new Supplier();delivered(ready,normal);ready.y.r.scene=new i.f.l.u.g();ready.y.r.scene.property=new i.f.l.u.p<Object>();ok(!LayoutGeometry1937.equivalent(ready,p,q,normal),"same session registry replaced scene dispatches");delivered(ready,normal);ready.y.r.scene.property=new i.f.l.u.p<Object>();ok(!LayoutGeometry1937.equivalent(ready,p,q,normal),"same scene replaced display property dispatches");delivered(ready,normal);ready.y.r.a.p=new PreviewView();ok(!LayoutGeometry1937.equivalent(ready,p,q,normal),"same manager replaced preview dispatches");delivered(ready,normal);ready.y.r.a.p.height=1500;ok(!LayoutGeometry1937.equivalent(ready,p,q,normal),"same preview size changed dispatches");delivered(ready,normal);ready.y.r.a.b=new Supplier();ok(!LayoutGeometry1937.equivalent(ready,p,q,normal),"same manager supplier replaced dispatches");
  LayoutGeometry1937.beginDelivery(ready,normal);ready.y.r.scene.property=new i.f.l.u.p<Object>();LayoutGeometry1937.markDelivery(ready,normal);ok(!LayoutGeometry1937.equivalent(ready,p,q,normal),"property changed during delivery cannot cache");
  
  ready.y.v=false;delivered(ready,normal);ok(LayoutGeometry1937.equivalent(ready,p,q,normal),"rect-only helper state fast path");ready.y.v=true;ok(!LayoutGeometry1937.equivalent(ready,p,q,normal),"helper ratio-init becomes ready dispatches");delivered(ready,normal);ok(LayoutGeometry1937.equivalent(ready,p,q,normal),"ratio initialized helper fast path");
  RectF empty=new RectF(0,0,0,0);delivered(ready,empty);ok(!LayoutGeometry1937.equivalent(ready,p,q,empty),"native empty sentinel cannot prove successful display delivery");RectF reversed=new RectF(742,1120,0,131);delivered(ready,reversed);ok(!LayoutGeometry1937.equivalent(ready,p,q,normal),"negative display dimensions cannot populate success cache");
  Class<?> snapshot=Class.forName("com.hiro.ulike.LayoutGeometry1937$Snapshot");for(Field field:snapshot.getDeclaredFields()){ok(field.getType().isPrimitive()||field.getType()==java.lang.ref.WeakReference[].class,"cache holds only primitives and weak identities: "+field);}
  System.out.println("{\"status\":\"passed\",\"checks\":"+checks+",\"device_tested\":false}");
 }
}
