#!/usr/bin/env python3
"""Run actual production AsyncSave/SaveQueue across scripted native ABI boundaries."""
from pathlib import Path
import json, subprocess, importlib.util

def test(root,work):
    root,work=Path(root),Path(work)/'host-save1944';work.mkdir(parents=True,exist_ok=True)
    spec=importlib.util.spec_from_file_location('save_baseline1935',root/'host_save_baseline1935.py');base=importlib.util.module_from_spec(spec);spec.loader.exec_module(base)
    fixtures=dict(base.FIXTURES)
    fixtures['android/graphics/Bitmap.java']='''package android.graphics; public class Bitmap {public enum Config{ARGB_8888,HARDWARE} public static volatile boolean failCopy;public static volatile int copies;public int[] pixels;public boolean premult=true,gainmap;boolean recycled;public Bitmap(int[] p){pixels=p;}public int getWidth(){return 2;}public int getHeight(){return 2;}public int getAllocationByteCount(){return pixels.length*4;}public Config getConfig(){return Config.ARGB_8888;}public boolean isPremultiplied(){return premult;}public boolean hasGainmap(){return gainmap;}public Bitmap copy(Config c,boolean m){copies++;if(failCopy)throw new OutOfMemoryError("scripted copy");return new Bitmap(pixels.clone());}public void recycle(){recycled=true;}public boolean isRecycled(){return recycled;}}'''
    fixtures['android/app/ActivityManager.java']='''package android.app;public class ActivityManager{public static class MemoryInfo{public boolean lowMemory;public long availMem,threshold;}}'''
    fixtures['com/hiro/ulike/SaveQuality2.java']='''package com.hiro.ulike;public class SaveQuality2{public static volatile boolean live=true;public static volatile int failures;public static boolean largeFixed;public static int[] output186(int width,int height,int rotation,boolean fixed){return fixed&&largeFixed?new int[]{5712,4284}:new int[]{width,height};}public static class MemoryManager{public static volatile boolean low;public void getMemoryInfo(android.app.ActivityManager.MemoryInfo info){info.lowMemory=low;info.availMem=1024L*1024*1024;info.threshold=64L*1024*1024;}}public static class App{public Object getSystemService(String name){return new MemoryManager();}}public static Object app186(){return new App();}public static boolean isFixed245Enabled(){return AsyncSave1935.fixed(live);}public static void showSaveFailure(){failures++;}}'''
    fixtures['i/f/l/n/q/y/n.java']='''package i.f.l.n.q.y;import android.graphics.Bitmap;public class n{public static Bitmap watermark;public static Bitmap f(){return watermark;}}'''
    fixtures['i/p/a/t/e.java']='''package i.p.a.t;import android.graphics.Bitmap;public class e{public static Bitmap d(Bitmap image,Bitmap watermark,int direction,double size,double margin){Bitmap result=new Bitmap(image.pixels.clone());result.pixels[3]^=watermark.pixels[0];return result;}}'''
    fixtures['i/o/a/b1/a/b/f/a.java']='''package i.o.a.b1.a.b.f;import i.o.a.q.c.c.b.e;public class a{public e a;public c b;public e.c c;public a(c listener){b=listener;c=(success,message,path,error)->b.b(success,a.e,path,error);a=new e(c);}public interface c{void a();void b(boolean s,int n,String p,String e);}}'''
    fixtures['com/hiro/ulike/SaveHarness1935.java']=r'''package com.hiro.ulike;
import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;import android.graphics.Bitmap;
public class SaveHarness1935 {
 static int assertions;static synchronized void check(boolean yes,String why){assertions++;if(!yes)throw new AssertionError(why);}
 static final BlockingQueue<Photo> preparing=new LinkedBlockingQueue<Photo>(),encoding=new LinkedBlockingQueue<Photo>();
 static final List<String> completed=Collections.synchronizedList(new ArrayList<String>());
 static final AtomicInteger encoderActive=new AtomicInteger(),peak=new AtomicInteger(),codecAllocated=new AtomicInteger(),codecPeak=new AtomicInteger();
 static volatile int finishes;static volatile boolean fast;static volatile int failureId,failureBeforeEncoding;
 static final CountDownLatch uiEntered=new CountDownLatch(1),uiRelease=new CountDownLatch(1);
 static class Photo{final Bitmap image;final int id,noise,rotation,direction;final boolean colour,fixed;final CountDownLatch processed=new CountDownLatch(1),saved=new CountDownLatch(1);Photo(Bitmap b,int r,int d){image=b;id=ShotContext1932.forBitmap(b).id;noise=AsyncSave1935.settings(PhotoDetail.live).noiseLevel;colour=AsyncSave1935.chroma(ChromaPipeline177.live);fixed=SaveQuality2.isFixed245Enabled();rotation=r;direction=d;}}
 public static String encode(i.o.a.q.c.c.b.e controller,Bitmap image,int rotation,int direction)throws Exception{
  Photo p=new Photo(image,rotation,direction);preparing.add(p);if(!fast&&!p.processed.await(5,TimeUnit.SECONDS))throw new AssertionError("processing timeout");
  if(p.id==failureBeforeEncoding)throw new IllegalStateException("scripted correction failure");
  AsyncSave1935.encoding(image);int allocated=codecAllocated.incrementAndGet();codecPeak.accumulateAndGet(allocated,Math::max);controller.e=p.id;controller.f=image.getHeight();int active=encoderActive.incrementAndGet();peak.accumulateAndGet(active,Math::max);encoding.add(p);
  try{if(!fast&&!p.saved.await(5,TimeUnit.SECONDS))throw new AssertionError("encoder timeout");if(image.isRecycled())throw new AssertionError("encoder pixels recycled");if(p.id==failureId)throw new IllegalStateException("scripted encode failure");return "photo-"+p.id;}finally{codecAllocated.decrementAndGet();encoderActive.decrementAndGet();}
 }
 static Photo next(BlockingQueue<Photo> q,String why)throws Exception{Photo p=q.poll(5,TimeUnit.SECONDS);check(p!=null,why);return p;}
 static void await(java.util.function.BooleanSupplier p,String why)throws Exception{long end=System.nanoTime()+5000000000L;while(!p.getAsBoolean()&&System.nanoTime()<end)Thread.sleep(2);check(p.getAsBoolean(),why);}
 static Bitmap source(int id,int n){Bitmap b=new Bitmap(new int[]{n,n+1,n+2,n+3});ShotContext1932.bind(b,id);i.f.l.n.s.a.b().image=b;return b;}
 public static class Camera{final int code;Camera(int code){this.code=code;}public int D1(){return code;}}
 public static void main(String[]args)throws Exception{
  i.o.a.b1.a.b.f.a manager=new i.o.a.b1.a.b.f.a(new i.o.a.b1.a.b.f.a.c(){public void a(){finishes++;}public void b(boolean ok,int id,String path,String error){if(ok)check(path.equals("photo-"+id),"receipt controller bound to exact saved photo");completed.add(ok?path:"failure");if(path.equals("photo-101")){uiEntered.countDown();try{if(!uiRelease.await(5,TimeUnit.SECONDS))throw new AssertionError("UI hold timeout");}catch(InterruptedException e){throw new AssertionError(e);}}}});
  Bitmap firstSource=source(101,11);AsyncSave1935.submitAuto(manager,90,2);Photo one=next(preparing,"first preparation");await(()->finishes==1,"capture released before final correction");check(SaveQueue1935.nativeBytes()==32,"input plus anticipated final native bitmaps explicitly budgeted");check(!SaveQueue1935.memoryAllows(SaveQueue1935.nativeBytes()+SaveQueue1935.RESERVE+95,4),"queued native bitmap bytes subtracted from Java headroom");check(SaveQueue1935.memoryAllows(SaveQueue1935.nativeBytes()+SaveQueue1935.RESERVE+96,4),"tracked native allocation exact safe bound");check(!AsyncSave1935.captureBlocked(),"second real capture accepted during first correction");SaveQuality2.MemoryManager.low=true;check(AsyncSave1935.captureBlocked(),"physical low-memory signal blocks overlapping capture");SaveQuality2.MemoryManager.low=false;check(!AsyncSave1935.captureBlocked(),"physical memory recovery restores safe capture admission");CaptureYuv.state.yuv.w=6000;CaptureYuv.state.yuv.h=4000;check(AsyncSave1935.captureBlocked(),"current larger reader geometry budgets concurrent reserve");CaptureYuv.state.yuv.w=2;CaptureYuv.state.yuv.h=2;CaptureYuv.ready=false;check(AsyncSave1935.captureBlocked(),"reconfiguring reader never overlaps");CaptureYuv.ready=true;CaptureYuv.state.yuv.format=256;check(AsyncSave1935.captureBlocked(),"unverified input route remains serial");CaptureYuv.state.yuv.format=35;
  check(one.image!=firstSource,"independent exact owned pixels");firstSource.pixels[0]=999;check(one.image.pixels[0]==11,"renderer source reuse cannot corrupt photo");
  PhotoDetail.live=new PhotoDetail.Settings(3);ChromaPipeline177.live=false;SaveQuality2.live=false;source(202,21);AsyncSave1935.submitAuto(manager,270,1);await(()->finishes==2,"second copied capture released without waiting for first save");check(preparing.isEmpty(),"only one correction stage before encoding boundary");
  one.processed.countDown();Photo firstEncoder=next(encoding,"first encode");check(firstEncoder==one,"same final owned image");Photo two=next(preparing,"second correction overlaps first encoder");check(encoderActive.get()==1,"encoder active while next correction works");
  PhotoDetail.live=new PhotoDetail.Settings(4);ChromaPipeline177.live=true;SaveQuality2.live=true;source(303,31);AsyncSave1935.submitAuto(manager,180,3);await(()->finishes==3,"third captured waiting slot");check(SaveQueue1935.count()==3,"three bounded photo ownerships");check(AsyncSave1935.captureBlocked(),"fourth shutter blocked at real photo capacity");check(SaveQueue1935.maximumPixels()==4,"pending geometry accounted");
  two.processed.countDown();Thread.sleep(30);check(encoding.isEmpty(),"second encoder waits for first close");check(preparing.isEmpty(),"third correction waits for occupied correction boundary");
  one.saved.countDown();check(uiEntered.await(5,TimeUnit.SECONDS),"first UI completion deliberately held");Photo secondEncoder=next(encoding,"second encoding proceeds despite blocked completion UI");check(secondEncoder==two,"second exact pixels");Photo three=next(preparing,"third correction overlaps second encode");
  check(one.noise==1&&one.colour&&one.fixed,"first captured options immutable");check(two.noise==3&&!two.colour&&!two.fixed,"second captured options immutable");check(three.noise==4&&three.colour&&three.fixed,"third captured options immutable");check(one.rotation==90&&one.direction==2&&two.rotation==270&&two.direction==1,"native orientation ordering unchanged");check(one.image.isRecycled(),"first image freed only after saved close");
  three.processed.countDown();two.saved.countDown();Photo thirdEncoder=next(encoding,"third encoding without blocked UI dependency");check(thirdEncoder==three,"FIFO encode identity");three.saved.countDown();await(()->SaveQueue1935.count()==0,"save ownership released after file completion independent of UI");check(ExitJobs185.count()==3,"all pending completion callbacks retain exit guard");check(peak.get()==1,"hardware encoder never concurrent");check(codecPeak.get()==1,"codec constructor guarded before allocation");check(completed.equals(Arrays.asList("photo-101")),"main UI callbacks remain FIFO");
  uiRelease.countDown();await(()->ExitJobs185.count()==0,"exit guard held through final UI completion");check(completed.equals(Arrays.asList("photo-101","photo-202","photo-303")),"ordered exact receipts");check(finishes==3,"capture finished exactly once per shot");
  int receiptStart=completed.size();fast=false;source(808,81);AsyncSave1935.submitAuto(manager,0,0);Photo orderedA=next(preparing,"FIFO failure prior photo correction");orderedA.processed.countDown();next(encoding,"FIFO failure prior encoder active");await(()->!AsyncSave1935.captureBlocked(),"capture ready for early failing correction");failureBeforeEncoding=909;source(909,91);AsyncSave1935.submitAuto(manager,0,0);Photo failedB=next(preparing,"second correction scheduled while prior encoder active");failedB.processed.countDown();Thread.sleep(40);check(completed.size()==receiptStart,"early correction failure cannot overtake prior writer receipt");check(SaveQueue1935.count()==2,"failed correction retains FIFO terminal turn");orderedA.saved.countDown();await(()->ExitJobs185.count()==0,"early correction failure drains in terminal order");check(completed.subList(receiptStart,completed.size()).equals(Arrays.asList("photo-808","failure")),"success and early correction failure receipts FIFO");check(failedB.image.isRecycled(),"failed correction exact input released");failureBeforeEncoding=0;
  fast=true;failureId=404;source(404,41);AsyncSave1935.submitAuto(manager,0,0);next(preparing,"failed preparation enters");next(encoding,"failed encoder enters");await(()->ExitJobs185.count()==0,"failed encode balances queue and UI guard");check(completed.get(completed.size()-1).equals("failure"),"failed save notified as failure");check(SaveQueue1935.count()==0,"failed slot freed");failureId=0;
  Bitmap borrowed=source(505,51);Bitmap.failCopy=true;int before=finishes;fast=false;AsyncSave1935.submitAuto(manager,0,0);Photo serial=next(preparing,"copy OOM serial exact fallback");check(serial.image==borrowed,"copy OOM retains pristine exact original");check(AsyncSave1935.captureBlocked(),"fallback source keeps shutter closed");check(finishes==before,"no early native callback in copy fallback");serial.processed.countDown();next(encoding,"serial fallback encode");serial.saved.countDown();await(()->ExitJobs185.count()==0,"serial fallback saved and notified");check(!borrowed.isRecycled(),"borrowed SDK bitmap never recycled");Bitmap.failCopy=false;
  fast=true;i.f.l.n.q.y.n.watermark=new Bitmap(new int[]{0x55});Bitmap markedSource=source(606,61);int copies=Bitmap.copies;AsyncSave1935.submitAuto(manager,0,0);Photo marked=next(preparing,"watermark direct owned preparation");next(encoding,"watermark encode");await(()->ExitJobs185.count()==0,"watermark completion");check(Bitmap.copies==copies,"no redundant full source copy for audited watermark route");check(marked.image!=markedSource,"watermark output owns separate image");check(markedSource.pixels[3]==64&&marked.image.pixels[3]==(64^0x55),"watermark input pristine and exact output");Bitmap hdr=source(607,62);hdr.gainmap=true;copies=Bitmap.copies;AsyncSave1935.submitAuto(manager,0,0);next(preparing,"gainmap route preparation");next(encoding,"gainmap route encode");await(()->ExitJobs185.count()==0,"gainmap completion");check(Bitmap.copies==copies+1,"gainmap preserves original copy route");
  Bitmap unpremult=source(608,63);unpremult.premult=false;copies=Bitmap.copies;AsyncSave1935.submitAuto(manager,0,0);next(preparing,"unpremult preparation");next(encoding,"unpremult encode");await(()->ExitJobs185.count()==0,"unpremult completion");check(Bitmap.copies==copies+1,"unpremult preserves original copy route");i.f.l.n.q.y.n.watermark=null;
  fast=false;SaveQuality2.live=false;source(1000,100);AsyncSave1935.submitAuto(manager,0,0);Photo nextTarget=next(preparing,"captured small output before preference switch");await(()->!AsyncSave1935.captureBlocked(),"small next planned output fits");SaveQuality2.largeFixed=true;SaveQuality2.live=true;check(AsyncSave1935.captureBlocked(),"current next fixed output target guard follows live preference change");SaveQuality2.largeFixed=false;nextTarget.processed.countDown();next(encoding,"previous photo fixed flag stays snapshotted");nextTarget.saved.countDown();await(()->ExitJobs185.count()==0,"planned next-target test balances");
  fast=false;SaveQuality2.largeFixed=true;source(1001,101);AsyncSave1935.submitAuto(manager,0,0);Photo fixed=next(preparing,"small input large fixed output preparation");check(SaveQueue1935.nativeBytes()==16+5712L*4284L*4L,"snapshot fixed245 target budgeted before normalize allocation");check(!SaveQueue1935.memoryAllows(SaveQueue1935.nativeBytes()+SaveQueue1935.RESERVE+95,4),"larger anticipated final allocation included in memory bound");fixed.processed.countDown();next(encoding,"fixed output encoder boundary");fixed.saved.countDown();await(()->ExitJobs185.count()==0,"large fixed output lease and memory cost released");SaveQuality2.largeFixed=false;fast=true;
  i.f.l.n.s.a.b().image=null;AsyncSave1935.submitAuto(manager,0,0);await(()->SaveQueue1935.count()==0,"missing source ownership cleanup");await(()->SaveQuality2.failures==1,"missing source failure shown");check(ExitJobs185.count()==0,"missing source exit guard balanced");
  check(!SaveQueue1935.memoryAllows(SaveQueue1935.RESERVE+95,4),"extra concurrent encoder reserve enforced below bound");check(SaveQueue1935.memoryAllows(SaveQueue1935.RESERVE+96,4),"safe exact memory bound");check(!SaveQueue1935.memoryAllows(Long.MAX_VALUE,32000001),"unknown large geometry serializes");check(AsyncSave1935.readiness(new Camera(7))==7,"native readiness errors retained");check(AsyncSave1935.readiness(new Camera(0))==0,"idle native readiness succeeds");
  for(int mode=1;mode<=3;mode++){android.os.Handler.mode=mode;source(700+mode,71);AsyncSave1935.submitAuto(manager,0,0);next(preparing,"failed main preparation");Photo e=next(encoding,"failed main encoder");await(()->SaveQueue1935.count()==0,"main failure saves and drains");await(()->ExitJobs185.count()==0,"main unavailable guard balances");check(e.image.isRecycled(),"main failure image freed");}
  android.os.Handler.mode=0;check(peak.get()==1&&codecPeak.get()==1&&codecAllocated.get()==0,"all failure paths release codec and keep allocation exclusive");await(()->SaveQueue1935.maximumPixels()==0&&SaveQueue1935.nativeBytes()==0,"completed geometry and native-cost references released");System.out.println("PASS save1944 assertions="+assertions+" scenarios=24 device_tested=false");
 }
}'''
    paths=[]
    for name,text in fixtures.items():
        p=work/'fixtures'/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(text);paths.append(p)
    classes=work/'classes';classes.mkdir(exist_ok=True)
    result=subprocess.run(['javac','-encoding','UTF-8','-source','8','-target','8','-d',str(classes),str(root/'AsyncSave1935.java'),str(root/'SaveQueue1935.java')]+list(map(str,paths)),text=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT);(work/'compile.log').write_text(result.stdout)
    if result.returncode:raise RuntimeError(result.stdout)
    result=subprocess.run(['java','-Xmx256m','-cp',str(classes),'com.hiro.ulike.SaveHarness1935'],text=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,timeout=35);(work/'result.txt').write_text(result.stdout)
    if result.returncode:raise RuntimeError(result.stdout)
    count=int(result.stdout.split('assertions=')[1].split()[0]);data={'suite':'save1944','status':'passed','passed':True,'assertions':count,'scenarios':24,'device_tested':False};(work/'result.json').write_text(json.dumps(data,indent=2));return data
if __name__=='__main__':
    import sys;print(json.dumps(test(Path(__file__).parent,Path(sys.argv[1])),indent=2))
