#!/usr/bin/env python3
"""Build the independent arm64 GLES3.1 integer backend with pinned NDK r27c."""
import argparse, hashlib, json, pathlib, re, subprocess
NDK_REVISION='27.2.12479018'
def run(args):
    result=subprocess.run([str(x) for x in args],text=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT)
    if result.returncode:raise RuntimeError(result.stdout)
    return result.stdout
def shader_header(source,output):
    names=['fusion_sums1949','pack_rgb1949','residual1949']
    text='/* Generated byte-for-byte from tracked integer shader sources. */\n'
    for name in names:
        shader=(source/(name+'.comp')).read_text()
        text+='static const char '+name+'_source[]=\n'+''.join(json.dumps(line+'\n')+'\n' for line in shader.splitlines())+';\n'
    path=output/'shader_sources1949.h';path.write_text(text);return path
def build(ndk,output):
    source=pathlib.Path(__file__).resolve().parent
    ndk=pathlib.Path(ndk).resolve();output=pathlib.Path(output).resolve();output.mkdir(parents=True,exist_ok=True)
    if not re.search(r'^Pkg.Revision\s*=\s*'+re.escape(NDK_REVISION)+r'\s*$',(ndk/'source.properties').read_text(),re.M):
        raise RuntimeError('NDK revision must be '+NDK_REVISION)
    tools=ndk/'toolchains/llvm/prebuilt/linux-x86_64/bin';cc=tools/'aarch64-linux-android26-clang'
    target=output/'libulike_gpu1949.so';shader_header(source,output)
    flags=['-std=c11','-O3','-shared','-fPIC','-fvisibility=hidden','-fno-fast-math','-ffp-contract=off',
        '-Wl,--no-undefined','-Wl,--build-id=sha1','-Wl,-z,max-page-size=16384',
        '-Wl,-soname,libulike_gpu1949.so','-Wall','-Wextra','-Werror','-I'+str(output)]
    run([cc,*flags,source/'gpu1949.c','-lEGL','-lGLESv3','-o',target])
    elf=run([tools/'llvm-readelf','-h','-d','-Ws','--program-headers','--wide',target])
    exports=['Java_com_hiro_ulike_GpuInteger1949_'+name for name in ['nativeAbi','fusionSumsNative','aggregateNative']]
    for name in exports:
        if name not in elf:raise RuntimeError('Missing JNI export '+name)
    if 'AArch64' not in elf:raise RuntimeError('Unexpected native target')
    needed=re.findall(r'\(NEEDED\).*?\[(.*?)\]',elf)
    if not {'libEGL.so','libGLESv3.so'}.issubset(needed) or any(name not in {'libEGL.so','libGLESv3.so','libc.so','libdl.so','libm.so'} for name in needed):
        raise RuntimeError('Unexpected system library dependencies: '+str(needed))
    alignments=[int(line.split()[-1],0) for line in elf.splitlines() if line.strip().startswith('LOAD ')]
    if not alignments or any(value<16384 for value in alignments):raise RuntimeError('ELF LOAD alignment below16KB')
    (output/'native1949-readelf.txt').write_text(elf)
    tracked=[source/'gpu1949.c',source/'build_native1949.py']+sorted(source.glob('*.comp'))
    report={'schema':'ulike-native1949-v1','ndk_revision':NDK_REVISION,'clang_version':run([cc,'--version']).splitlines()[0],
        'target':'aarch64-linux-android26','flags':[value if not value.startswith('-I') else '-I<generated-shader-header>' for value in flags],
        'file':target.name,'bytes':target.stat().st_size,
        'sha256':hashlib.sha256(target.read_bytes()).hexdigest(),'exports':exports,'needed_libraries':needed,
        'load_segment_alignments':alignments,'integer_shaders_only':True,'minimum_gles':'3.1',
        'minimum_compute_storage_blocks':5,'shared_halo_tile':'8x8+4','fence_timeout_ns':200000000,
        'float_fusion_retained_on_cpu':True,'intermediate_packed_readback':False,
        'cached_programs_context_buffer_capacity':True,'image_uploads_always_fresh':True,
        'destination_commit_after_success_only':True,'camera_context_reused':False,'physical_android_tested':False,
        'sources':{path.name:hashlib.sha256(path.read_bytes()).hexdigest() for path in tracked}}
    (output/'native-build1949.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report));return report
if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--ndk',required=True);parser.add_argument('--output',required=True)
    args=parser.parse_args();build(args.ndk,args.output)
