package com.hiro.ulike;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.ContentResolver;
import android.content.Intent;
import android.os.Handler;
import android.os.Looper;
import android.preference.Preference;
import java.io.*;
import java.lang.reflect.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.zip.*;

/** Fault tests against the actual production helper, with deterministic Android boundaries. */
public final class TraceAudit1965 {
    static int checks;
    static final int SEGMENT=128*1024,SNAPSHOT=256*1024;
    static void check(boolean value,String message){checks++;if(!value)throw new AssertionError(message);}
    static byte[] bytes(File f)throws Exception{return Files.readAllBytes(f.toPath());}
    static String text(File f)throws Exception{return new String(bytes(f),StandardCharsets.UTF_8);}
    static String repeat(char c,int n){char[] a=new char[n];Arrays.fill(a,c);return new String(a);}
    static List<File> files(File dir){File[] a=dir.listFiles((d,n)->n.endsWith(".jsonl"));List<File> v=new ArrayList<File>();if(a!=null)Collections.addAll(v,a);Collections.sort(v,Comparator.comparing(File::getName));return v;}
    static String contents(File dir)throws Exception{StringBuilder b=new StringBuilder();for(File f:files(dir))b.append(text(f));return b.toString();}
    static void clean(File f)throws Exception{if(!f.exists())return;try(java.util.stream.Stream<Path>s=Files.walk(f.toPath())){List<Path>a=new ArrayList<Path>();s.forEach(a::add);Collections.sort(a,Comparator.reverseOrder());for(Path p:a)Files.delete(p);}}
    static CameraTrace1965.Storage store(File root,String session)throws Exception{return new CameraTrace1965.Storage(root,session);}
    static String line(int n){return "{\"sequence\":"+n+",\"detail\":\""+repeat('q',350)+"\"}\n";}
    static void bounds(File dir,int count,long size,String kind)throws Exception{List<File>a=files(dir);check(a.size()<=count,kind+" retained file count");long total=0;for(File f:a){check(f.length()<=size,kind+" per-file hard cap");total+=f.length();byte[]b=bytes(f);check(b.length==0||b[b.length-1]=='\n',kind+" complete final record");}check(total<=count*size,kind+" total disk bound");}
    static void storage(File base)throws Exception{
        File root=new File(base,"storage");clean(root);root.mkdirs();CameraTrace1965.Storage s=store(root,"first-process");
        s.append("{\"marker\":\"pre-rotation\"}\n",true);
        for(int i=0;i<4300;i++)s.append(line(i),i%511==0);
        s.append("{\"marker\":\"recent-critical\"}\n",true);
        File rolling=new File(root,"rolling"),protectedDir=new File(root,"protected");bounds(rolling,8,SEGMENT,"rolling");
        check(files(rolling).size()==8,"all eight rolling slots can be populated");check(!contents(rolling).contains("pre-rotation"),"oldest segment is evicted");check(contents(rolling).contains("recent-critical"),"latest critical event persists immediately");
        File first=s.freeze("anomaly","timeout",41);byte[] frozen=bytes(first);check(first.getParentFile().equals(protectedDir),"snapshot is outside normal rotation");check(first.length()<=SNAPSHOT,"protected snapshot hard cap");check(text(first).contains("recent-critical"),"snapshot retains newest context");
        s.append("{\"marker\":\"after-first-freeze\"}\n",true);check(Arrays.equals(frozen,Arrays.copyOf(bytes(first),frozen.length)),"follow-up appends preserve original pre-trigger context");check(text(first).contains("after-first-freeze"),"active incident includes post-trigger lifecycle context");
        File user=s.freeze("user","export",41);byte[] userBytes=bytes(user);check(!user.equals(first),"user snapshot explicitly freezes its own context");check(text(user).contains("after-first-freeze"),"user freeze includes events available at request");
        s.append("{\"marker\":\"after-user-freeze\"}\n",true);check(!text(user).contains("after-user-freeze"),"user snapshot immutable after later events");
        File next=s.freeze("anomaly","timeout",42);check(!next.equals(first),"new incident epoch creates protected evidence");check(files(protectedDir).size()==3,"three protected snapshots retained");
        for(int i=4300;i<8900;i++)s.append(line(i),i%511==0);s.append("{\"marker\":\"rolling-after-snapshot\"}\n",true);
        check(Arrays.equals(userBytes,bytes(user)),"rolling eviction cannot alter protected user snapshot");check(first.exists(),"normal rotation cannot evict protected anomaly");
        ByteArrayOutputStream zip=new ByteArrayOutputStream();s.exportZip(zip);Map<String,byte[]> entries=new LinkedHashMap<String,byte[]>();try(ZipInputStream in=new ZipInputStream(new ByteArrayInputStream(zip.toByteArray()))){for(ZipEntry e;(e=in.getNextEntry())!=null;){ByteArrayOutputStream data=new ByteArrayOutputStream();byte[]b=new byte[8192];for(int n;(n=in.read(b))!=-1;)data.write(b,0,n);entries.put(e.getName(),data.toByteArray());}}
        int snapshots=0,segments=0;boolean exactUser=false;for(Map.Entry<String,byte[]>e:entries.entrySet()){String n=e.getKey();check(!n.contains("..")&&!n.startsWith("/"),"safe relative ZIP entry");if(n.contains("snapshot-")&&n.endsWith(".jsonl")){snapshots++;check(e.getValue().length<=SNAPSHOT,"ZIP protected snapshot cap");if(n.endsWith(user.getName()))exactUser=Arrays.equals(userBytes,e.getValue());}if(n.contains("segment-")&&n.endsWith(".jsonl")){segments++;check(e.getValue().length<=SEGMENT,"ZIP rolling segment cap");}}
        check(snapshots==3&&segments==8,"ZIP includes retained rolling and protected context");check(exactUser,"export preserves exact frozen user snapshot");check(zip.size()<2*1024*1024,"diagnostic export remains bounded");
        s.freeze("anomaly","timeout",43);s.freeze("anomaly","timeout",44);bounds(protectedDir,3,SNAPSHOT,"protected");check(files(protectedDir).size()==3,"oldest protected snapshots rotate separately");
        s.markClean();s.close();CameraTrace1965.Storage reopened=store(root,"second-process");check(!reopened.priorOpen,"clean session marker survived reopening");check("first-process".equals(reopened.priorSession),"previous process identity preserved");check(contents(rolling).contains("rolling-after-snapshot"),"normal records survive process reopen");check(files(protectedDir).size()==3,"protected records survive process reopen");
        reopened.close();List<File> tails=files(rolling);File tail=tails.get(tails.size()-1);byte[]partial="{\"marker\":\"CUT_OFF".getBytes(StandardCharsets.UTF_8);Files.write(tail.toPath(),partial,StandardOpenOption.APPEND);CameraTrace1965.Storage recovered=store(root,"third-process");check(recovered.recoveredTailBytes==partial.length,"partial final record recovered and counted exactly");check(!contents(rolling).contains("CUT_OFF"),"partial record removed before next append");recovered.append("{\"marker\":\"after-recovery\"}\n",true);check(contents(rolling).contains("after-recovery"),"storage continues after partial-tail recovery");bounds(rolling,8,SEGMENT,"recovered rolling");recovered.markClean();recovered.close();
    }
    static void incidentWindow(File base)throws Exception {
        File root=new File(base,"incident-window");clean(root);root.mkdirs();CameraTrace1965.Storage s=store(root,"window-process");
        for(int i=0;i<1200;i++)s.append(line(i),false);s.append("{\"marker\":\"immediate-pre-trigger\"}\n",true);
        File incident=s.freeze("anomaly","five_second_test",77);byte[] pre=bytes(incident);check(pre.length<=SNAPSHOT/2,"anomaly reserves half snapshot for post-trigger evidence");check(text(incident).contains("immediate-pre-trigger"),"anomaly pre-trigger tail includes most recent context");
        File user=s.freeze("user","freeze-during-incident",77);byte[] immutableUser=bytes(user);check(immutableUser.length>SNAPSHOT/2,"explicit user snapshot retains full available pre-request context");
        s.append("{\"marker\":\"follow-up-within-window\"}\n",true);check(text(incident).contains("follow-up-within-window"),"anomaly appends scalar follow-up inside five seconds");check(Arrays.equals(pre,Arrays.copyOf(bytes(incident),pre.length)),"post-trigger append never mutates frozen pre-trigger bytes");check(Arrays.equals(immutableUser,bytes(user)),"user snapshot remains immutable while incident follows up");
        android.os.SystemClock.offset+=5001;s.append("{\"marker\":\"after-five-second-window\"}\n",true);check(!text(incident).contains("after-five-second-window"),"post-trigger window expires after five seconds");check(contents(new File(root,"rolling")).contains("after-five-second-window"),"expired follow-up still retained in ordinary rolling log");check(Arrays.equals(immutableUser,bytes(user)),"user freeze unchanged after incident window expires");android.os.SystemClock.offset=0;
        File capped=s.freeze("anomaly","cap_test",78);for(int i=1200;i<2300;i++)s.append(line(i),false);s.append("{\"marker\":\"cap-tail-check\"}\n",true);check(capped.length()<=SNAPSHOT,"live incident follow-up cannot exceed 256KiB cap");byte[] full=bytes(capped);check(full[full.length-1]=='\n',"incident cap keeps complete JSONL records");s.markClean();s.close();
    }
    static void pendingFailures(File base)throws Exception {
        File root=new File(base,"pending-failures");clean(root);File protectedDir=new File(root,"protected");protectedDir.mkdirs();
        File stale=new File(protectedDir,"snapshot-00000000000000000009.jsonl.pending");Files.write(stale.toPath(),"aborted-temporary".getBytes(StandardCharsets.UTF_8));CameraTrace1965.Storage s=store(root,"pending-process");check(!stale.exists(),"startup removes abandoned snapshot temporary files");s.append("{\"marker\":\"before-storage-fault\"}\n",true);
        Path failed=new File(protectedDir,"snapshot-00000000000000000001.jsonl.pending").toPath();Files.createSymbolicLink(failed,Paths.get("/dev/full"));boolean threw=false;try{s.freeze("anomaly","forced-write-failure",80);}catch(IOException expected){threw=true;}check(threw,"actual filesystem write failure injected through /dev/full");check(!Files.exists(failed,LinkOption.NOFOLLOW_LINKS),"failed snapshot write removes pending temporary");check(files(protectedDir).isEmpty(),"failed pending snapshot never becomes committed evidence");
        File good=s.freeze("user","after-storage-fault",81);check(good.exists()&&text(good).contains("before-storage-fault"),"store remains usable after snapshot write failure");byte[] validProtected=bytes(good),broken="{\"marker\":\"PARTIAL_PROTECTED".getBytes(StandardCharsets.UTF_8);Files.write(good.toPath(),broken,StandardOpenOption.APPEND);
        ByteArrayOutputStream archive=new ByteArrayOutputStream();s.exportZip(archive);boolean liveSafe=false;try(ZipInputStream zipped=new ZipInputStream(new ByteArrayInputStream(archive.toByteArray()))){for(ZipEntry e;(e=zipped.getNextEntry())!=null;){if(e.getName().endsWith(good.getName())){ByteArrayOutputStream item=new ByteArrayOutputStream();byte[] b=new byte[1024];for(int n;(n=zipped.read(b))!=-1;)item.write(b,0,n);liveSafe=Arrays.equals(validProtected,item.toByteArray());}}}check(liveSafe,"same-process export omits partially written protected final record");s.markClean();s.close();
        CameraTrace1965.Storage recovered=store(root,"after-protected-tail");check(recovered.recoveredTailBytes==broken.length,"protected partial-tail bytes recovered and counted exactly");check(Arrays.equals(validProtected,bytes(good)),"protected tail repair preserves entire valid snapshot prefix");recovered.append("{\"marker\":\"after-protected-recovery\"}\n",true);check(contents(new File(root,"rolling")).contains("after-protected-recovery"),"store continues after protected-tail recovery");recovered.markClean();recovered.close();
    }
    static void uncleanWrite(File base)throws Exception{File root=new File(base,"unclean");clean(root);root.mkdirs();CameraTrace1965.Storage s=store(root,"killed-process");s.append("{\"marker\":\"persisted-before-kill\"}\n",true);File f=s.freeze("anomaly","preview_timeout",900);check(f.exists(),"critical protected evidence flushed before process death");/* No close or markClean: JVM exit simulates process termination. */}
    static void uncleanRead(File base)throws Exception{File root=new File(base,"unclean");CameraTrace1965.Storage s=store(root,"replacement-process");check(s.priorOpen,"unclean prior JVM is identified");check("killed-process".equals(s.priorSession),"unclean prior session ID retained");check(contents(new File(root,"rolling")).contains("persisted-before-kill"),"critical tail retained across distinct JVMs");check(files(new File(root,"protected")).size()==1,"protected incident retained across distinct JVMs");s.markClean();s.close();}
    static Object field(String name)throws Exception{Field f=CameraTrace1965.class.getDeclaredField(name);f.setAccessible(true);return f.get(null);}
    interface Condition{boolean ok()throws Exception;}
    static void until(Condition condition,String what)throws Exception{long end=System.nanoTime()+TimeUnit.SECONDS.toNanos(6);while(System.nanoTime()<end){if(condition.ok())return;Thread.sleep(10);}throw new AssertionError("timed out: "+what);}
    static File helperRoot(File files)throws Exception{List<File>a=new ArrayList<File>();if(files.exists())try(java.util.stream.Stream<Path>s=Files.walk(files.toPath())){s.filter(p->p.getFileName().toString().equals("rolling")).forEach(p->a.add(p.toFile().getParentFile()));}return a.size()==1?a.get(0):null;}
    static void mainUi()throws Exception{Handler.dispatchAll();}
    static void open(Activity activity)throws Exception{AlertDialog.last=null;CameraTrace1965.open(new Preference(activity));mainUi();until(()->AlertDialog.last!=null,"diagnostic dialog");}
    static void cleanupRetry(File base)throws Exception {
        Looper.getMainLooper();File f=new File(base,"cleanup-retry");clean(f);f.mkdirs();Activity app=new Activity(f);android.os.SystemClock.armBootCleanupFault();CameraTrace1965.init(app);
        check(android.os.SystemClock.closeEntered.await(4,TimeUnit.SECONDS),"boot fault reaches real storage close/fsync boundary");Thread closing=(Thread)field("WRITER");Object closingStore=field("STORE");
        try {
            check(closing!=null&&closing.isAlive(),"failed writer remains initialization owner during cleanup");check(closingStore!=null,"failed writer store remains assigned through cleanup");check(app.filesDirCalls.get()==1,"only one writer opened the storage directory");
            for(int i=0;i<20;i++)CameraTrace1965.init(app);
            check(field("WRITER")==closing,"repeated init cannot replace a writer blocked in cleanup");check(field("STORE")==closingStore,"retry cannot replace store before previous close completes");check(app.filesDirCalls.get()==1,"retry cannot open a second writer against active closing files");
        } finally {android.os.SystemClock.closeRelease.countDown();}
        until(()->field("WRITER")==null&&field("STORE")==null,"failed writer cleanup ownership released");closing.join(1000);check(!closing.isAlive(),"failed writer terminates after releasing ownership");android.os.SystemClock.bootCleanupFault=false;
        CameraTrace1965.init(app);until(()->field("WRITER")!=null&&field("STORE")!=null,"new recorder starts after completed cleanup");Thread replacement=(Thread)field("WRITER");check(replacement!=closing&&replacement.isAlive(),"retry starts a new live writer after cleanup");check(app.filesDirCalls.get()==2,"successful retry opens storage exactly once more");
        CameraTrace1965.event("retry_after_cleanup",404,"accepted=1");until(()->{File root=helperRoot(f);return root!=null&&contents(new File(root,"rolling")).contains("retry_after_cleanup");},"new writer accepts and flushes events");check(field("STORE")!=closingStore,"replacement store survives old writer finalization");check(!app.filesOnMain,"fault recovery performs no caller-thread storage access");
    }
    static void helper(File base)throws Exception{
        // Initialize Looper on the caller thread before the recorder worker exists.
        Looper.getMainLooper();File f=new File(base,"helper");clean(f);f.mkdirs();Activity app=new Activity(f);long start=System.nanoTime();CameraTrace1965.init(app);check(System.nanoTime()-start<TimeUnit.SECONDS.toNanos(1),"init does not wait for disk on caller");until(()->helperRoot(f)!=null&&field("STORE")!=null,"storage initialized asynchronously");File root=helperRoot(f),rolling=new File(root,"rolling");until(()->contents(rolling).contains("process_start"),"process-start record persisted");String initial=contents(rolling);check(initial.contains(CameraTrace1965.VERSION),"process-start carries helper version");check(initial.contains("36"),"process-start carries API level");check(initial.contains("HOST_MODEL_1965"),"process-start carries model");check(initial.contains("prior")||initial.contains("unclean"),"process-start records prior session status");check(!app.filesOnMain,"storage directory accessed only on worker");
        int posts=Handler.posted;long normalStart=System.nanoTime();CameraTrace1965.event("normal_event",90,"safe=value\ncontrol=\u0000 "+repeat('z',1000));check(Handler.posted==posts,"normal event posts no UI work");until(()->contents(rolling).contains("normal_event"),"normal flush within bounded delay");check(System.nanoTime()-normalStart<TimeUnit.MILLISECONDS.toNanos(850),"normal event flush obeys 500ms interval with host scheduling allowance");String normal=contents(rolling);check(!normal.contains(repeat('z',200)),"scalar event field capped at 160 characters");check(normal.indexOf('\u0000')<0,"scalar control characters sanitized");
        CameraTrace1965.anomaly("helper_anomaly",91,"reason=host");until(()->files(new File(root,"protected")).size()>0,"critical anomaly protected promptly");int count=files(new File(root,"protected")).size();CameraTrace1965.anomaly("helper_anomaly",91,"reason=repeat");Thread.sleep(80);check(files(new File(root,"protected")).size()==count,"public anomaly repeated epoch coalesced");
        // Holding the writer's queue monitor produces deterministic overload without disk delay guesses.
        Object queue=field("QUEUE");Object storage=field("STORE");Object lock;try{lock=field("LOCK");}catch(NoSuchFieldException no){lock=queue;}synchronized(storage){synchronized(lock){String callerBefore=contents(rolling);start=System.nanoTime();for(int i=0;i<2000;i++)CameraTrace1965.event("queue_pressure",100+i,"i="+i);check(System.nanoTime()-start<TimeUnit.SECONDS.toNanos(2),"event enqueue never waits on file I/O");check(((Collection<?>)queue).size()<=256,"in-memory recorder queue remains bounded");check(callerBefore.equals(contents(rolling)),"caller cannot write log files while worker is stopped");}}until(()->contents(rolling).contains("dropped"),"overload drop count persisted");check(contents(rolling).matches("(?s).*dropped[^\\n]*[1-9][0-9]*.*"),"queue overflow reports nonzero dropped count");check(!app.filesOnMain&&!app.resolver.mainIo,"event/anomaly APIs perform no caller-thread file or provider work");
        // Explicit user request freezes before share work. The dialog chooses export/share.
        open(app);AlertDialog dialog=AlertDialog.last;check(dialog.items!=null&&dialog.items.length==2,"diagnostic snapshot and share actions available");List<File> priorSnapshots=files(new File(root,"protected"));String priorLatest=priorSnapshots.isEmpty()?"":priorSnapshots.get(priorSnapshots.size()-1).getName();dialog.clickItem(1);until(()->app.resolver.inserts>0,"user export provider insertion");until(()->app.resolver.updates>0,"user export pending publication");mainUi();until(()->{mainUi();return app.started!=null;},"share intent after successful pending publication");List<File> sharedSnapshots=files(new File(root,"protected"));File sharedSnapshot=sharedSnapshots.get(sharedSnapshots.size()-1);check(sharedSnapshot.getName().compareTo(priorLatest)>0,"user export explicitly freezes a new protected snapshot before sharing");check(text(sharedSnapshot).contains("kind=user reason=share_requested"),"frozen share snapshot records explicit user request");byte[] sharedFrozen=bytes(sharedSnapshot);ContentResolver resolver=app.resolver;check(Integer.valueOf(1).equals(resolver.insertedValues.get(0).get("is_pending")),"MediaStore export begins pending");check(Integer.valueOf(0).equals(resolver.updatedValues.get(0).get("is_pending")),"successful export clears pending");check(!resolver.mainIo,"provider export happens only on writer");Intent share=app.started.target==null?app.started:app.started.target;check(Intent.ACTION_SEND.equals(share.action),"standard Android ACTION_SEND export");check("application/zip".equals(share.type),"ZIP sharing MIME type");check((share.flags&Intent.FLAG_GRANT_READ_URI_PERMISSION)!=0,"share URI grants read permission");check((share.flags&Intent.FLAG_GRANT_WRITE_URI_PERMISSION)==0,"share URI never grants write permission");check(share.extras.get(Intent.EXTRA_STREAM)!=null,"share URI supplied as stream");check(share.extras.get(Intent.EXTRA_STREAM).toString().startsWith("content://"),"share uses provider URI");check(resolver.data.values().iterator().next().length>0,"completed export contains bytes");byte[] archive=resolver.data.get((android.net.Uri)share.extras.get(Intent.EXTRA_STREAM));boolean sharedExact=false;try(ZipInputStream zipped=new ZipInputStream(new ByteArrayInputStream(archive))){for(ZipEntry e;(e=zipped.getNextEntry())!=null;){if(e.getName().endsWith(sharedSnapshot.getName())){ByteArrayOutputStream item=new ByteArrayOutputStream();byte[] chunk=new byte[1024];for(int n;(n=zipped.read(chunk))!=-1;)item.write(chunk,0,n);sharedExact=Arrays.equals(sharedFrozen,item.toByteArray());}}}check(sharedExact,"shared ZIP carries exact previously frozen user context");CameraTrace1965.event("after_share_freeze",909,"later=1");until(()->contents(rolling).contains("after_share_freeze"),"later event recorded after sharing");check(Arrays.equals(sharedFrozen,bytes(sharedSnapshot)),"shared user context immutable after later camera events");
        // Provider failures after insertion must delete abandoned pending entries and never launch share.
        app.started=null;resolver.failWrite=true;int deletes=resolver.deletes;open(app);AlertDialog.last.clickItem(1);final int writeDeletes=deletes;until(()->resolver.deletes>writeDeletes,"cleanup after output stream write failure");mainUi();check(app.started==null,"write failure cannot share partial archive");resolver.failWrite=false;
        app.started=null;resolver.failPublish=true;deletes=resolver.deletes;open(app);AlertDialog.last.clickItem(1);final int priorDeletes=deletes;until(()->resolver.deletes>priorDeletes,"cleanup after pending publication failure");mainUi();check(app.started==null,"publication failure cannot share pending URI");resolver.failPublish=false;
        // Cleanup itself can fail; recorder must remain alive and process the next critical event.
        resolver.failOpen=true;resolver.failDelete=true;final int failedDeletes=resolver.deletes;open(app);AlertDialog.last.clickItem(1);until(()->resolver.deletes>failedDeletes,"cleanup failure was attempted");mainUi();resolver.failOpen=false;resolver.failDelete=false;CameraTrace1965.event("after_export_cleanup_failure",999,"ok=1");until(()->contents(rolling).contains("after_export_cleanup_failure"),"worker survives export and cleanup failures");check(((Thread)field("WRITER")).isAlive(),"writer thread stays alive through share failures");bounds(rolling,8,SEGMENT,"helper rolling");bounds(new File(root,"protected"),3,SNAPSHOT,"helper protected");
    }
    public static void main(String[] args)throws Exception{File base=new File(args[1]);base.mkdirs();String mode=args[0];if("storage".equals(mode)){storage(base);incidentWindow(base);pendingFailures(base);}else if("unclean-write".equals(mode))uncleanWrite(base);else if("unclean-read".equals(mode))uncleanRead(base);else if("cleanup-retry".equals(mode))cleanupRetry(base);else if("helper".equals(mode))helper(base);else throw new IllegalArgumentException(mode);System.out.println("checks="+checks);}
}
