#!/usr/bin/env python3
"""Run actual production AsyncSave/SaveQueue across scripted native ABI boundaries."""
from pathlib import Path
import json, subprocess, importlib.util

def test(root,work):
    root,work=Path(root),Path(work)/'host-save1945';work.mkdir(parents=True,exist_ok=True)
    spec=importlib.util.spec_from_file_location('save_baseline1935',root/'host_save_baseline1935.py');base=importlib.util.module_from_spec(spec);spec.loader.exec_module(base)
    fixtures=dict(base.FIXTURES)
    fixtures['android/os/Looper.java']='''package android.os;import java.util.concurrent.*;public class Looper{static final ThreadLocal<Looper>CURRENT=new ThreadLocal<Looper>();static final Looper MAIN=new Looper();final LinkedBlockingDeque<Runnable>queue=new LinkedBlockingDeque<Runnable>();public static Looper getMainLooper(){return MAIN;}public static Looper myLooper(){return CURRENT.get();}void loop(){CURRENT.set(this);for(;;)try{queue.takeFirst().run();}catch(InterruptedException ignored){}}static{Thread t=new Thread(()->MAIN.loop(),"fake-main");t.setDaemon(true);t.start();}}'''
    fixtures['android/os/HandlerThread.java']='''package android.os;public class HandlerThread extends Thread{private final Looper looper=new Looper();public static volatile int created;public final int priority;public HandlerThread(String name,int priority){super(name);this.priority=priority;created++;setDaemon(true);}public void run(){looper.loop();}public Looper getLooper(){return looper;}}'''
    fixtures['android/os/Handler.java']='''package android.os;public class Handler{public static volatile int mode,codecMode;final Looper looper;public Handler(Looper l){if(l==Looper.getMainLooper()&&mode==3)throw new OutOfMemoryError("handler allocation");looper=l;}public Looper getLooper(){return looper;}public boolean post(Runnable r){if(looper==Looper.getMainLooper()){if(mode==1)return false;if(mode==2)throw new OutOfMemoryError("post allocation");}else{if(codecMode==1)return false;if(codecMode==2)throw new OutOfMemoryError("codec post allocation");if(codecMode==3)throw new NoClassDefFoundError("codec post link");}looper.queue.addLast(r);return true;}public boolean postAtFrontOfQueue(Runnable r){looper.queue.addFirst(r);return true;}}'''
    fixtures['android/media/MediaCodec.java']='''package android.media;import java.io.*;import com.hiro.ulike.SaveHarness1935;public class MediaCodec{public static volatile boolean failStop,failRelease;boolean released;MediaCodec(){int n=SaveHarness1935.codecAllocated.incrementAndGet();SaveHarness1935.codecPeak.accumulateAndGet(n,Math::max);}public static MediaCodec createByCodecName(String n)throws IOException{return new MediaCodec();}public static MediaCodec createEncoderByType(String n)throws IOException{return new MediaCodec();}public void stop(){if(failStop){failStop=false;throw new IllegalStateException("scripted stop failure");}}public void release(){if(failRelease)throw new IllegalStateException("scripted release failure");if(released)throw new AssertionError("codec double release");released=true;SaveHarness1935.codecAllocated.decrementAndGet();}}'''
    fixtures['androidx/heifwriter/HeifWriter.java']='''package androidx.heifwriter;import java.io.*;import android.os.*;import android.media.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;import com.hiro.ulike.CodecDrain1945;public class HeifWriter{public static volatile CountDownLatch closingEntered,closingRelease;final Handler handler;final MediaCodec codec;final AtomicBoolean closed=new AtomicBoolean();HeifWriter(Handler h,MediaCodec c){handler=h;codec=c;}public void close(){if(!closed.compareAndSet(false,true))return;CountDownLatch entered=closingEntered,release=closingRelease;if(entered!=null){entered.countDown();try{if(!release.await(5,TimeUnit.SECONDS))throw new AssertionError("scripted close timeout");}catch(InterruptedException e){throw new AssertionError(e);}}handler.postAtFrontOfQueue(()->handler.postAtFrontOfQueue(()->{try{CodecDrain1945.stopAndRelease(codec);}catch(RuntimeException ignored){}}));}public static class Builder{public static volatile int mode;Handler handler;public Builder setHandler(Handler h){handler=h;return this;}public HeifWriter build()throws IOException{MediaCodec c=CodecDrain1945.createEncoderByType("image/vnd.android.heic");int fault=mode;mode=0;if(fault==1)throw new IOException("scripted builder IO failure after codec");if(fault==2)throw new IllegalStateException("scripted builder runtime failure after codec");if(fault==3)throw new OutOfMemoryError("scripted builder OOM after codec");if(fault==4){try{throw new IllegalStateException("scripted capability lookup failure");}catch(Exception ignored){c=CodecDrain1945.createByCodecName("fallback.hevc");}}if(fault==5){CodecDrain1945.releaseCodec(c);c=CodecDrain1945.createByCodecName("fallback.hevc");}return new HeifWriter(handler,c);}}}'''
    fixtures['android/graphics/Bitmap.java']='''package android.graphics; public class Bitmap {public enum Config{ARGB_8888,HARDWARE} public static volatile boolean failCopy;public static volatile int copies;public int[] pixels;public boolean premult=true,gainmap;boolean recycled;public Bitmap(int[] p){pixels=p;}public int getWidth(){return 2;}public int getHeight(){return 2;}public int getAllocationByteCount(){return pixels.length*4;}public Config getConfig(){return Config.ARGB_8888;}public boolean isPremultiplied(){return premult;}public boolean hasGainmap(){return gainmap;}public Bitmap copy(Config c,boolean m){copies++;if(failCopy)throw new OutOfMemoryError("scripted copy");return new Bitmap(pixels.clone());}public void recycle(){recycled=true;}public boolean isRecycled(){return recycled;}}'''
    fixtures['android/app/ActivityManager.java']='''package android.app;public class ActivityManager{public static class MemoryInfo{public boolean lowMemory;public long availMem,threshold;}}'''
    fixtures['com/hiro/ulike/SaveQuality2.java']='''package com.hiro.ulike;public class SaveQuality2{public static volatile boolean live=true;public static volatile int failures;public static boolean largeFixed;public static int[] output186(int width,int height,int rotation,boolean fixed){return fixed&&largeFixed?new int[]{5712,4284}:new int[]{width,height};}public static class MemoryManager{public static volatile boolean low;public void getMemoryInfo(android.app.ActivityManager.MemoryInfo info){info.lowMemory=low;info.availMem=1024L*1024*1024;info.threshold=64L*1024*1024;}}public static class App{public Object getSystemService(String name){return new MemoryManager();}}public static Object app186(){return new App();}public static boolean isFixed245Enabled(){return AsyncSave1935.fixed(live);}public static void showSaveFailure(){failures++;}}'''
    fixtures['i/f/l/n/q/y/n.java']='''package i.f.l.n.q.y;import android.graphics.Bitmap;public class n{public static Bitmap watermark;public static Bitmap f(){return watermark;}}'''
    fixtures['i/p/a/t/e.java']='''package i.p.a.t;import android.graphics.Bitmap;public class e{public static Bitmap d(Bitmap image,Bitmap watermark,int direction,double size,double margin){Bitmap result=new Bitmap(image.pixels.clone());result.pixels[3]^=watermark.pixels[0];return result;}}'''
    fixtures['i/o/a/b1/a/b/f/a.java']='''package i.o.a.b1.a.b.f;import i.o.a.q.c.c.b.e;public class a{public e a;public c b;public e.c c;public a(c listener){b=listener;c=(success,message,path,error)->b.b(success,a.e,path,error);a=new e(c);}public interface c{void a();void b(boolean s,int n,String p,String e);}}'''
    fixtures['com/hiro/ulike/SaveHarness1935.java']=r'''package com.hiro.ulike;
import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;import android.graphics.Bitmap;
public class SaveHarness1935 {
 static int assertions;static synchronized void check(boolean yes,String why){assertions++;if(!yes)throw new AssertionError(why);}
 static final BlockingQueue<Photo> preparing=new LinkedBlockingQueue<Photo>(),encoding=new LinkedBlockingQueue<Photo>();
 static final List<String> completed=Collections.synchronizedList(new ArrayList<String>());
 public static final AtomicInteger codecAllocated=new AtomicInteger(),codecPeak=new AtomicInteger();static final AtomicInteger encoderActive=new AtomicInteger(),peak=new AtomicInteger();
 static volatile int finishes;static volatile boolean fast;static volatile int failureId,failureBeforeEncoding;
 static final ExecutorService codecPrep=Executors.newSingleThreadExecutor(r->{Thread t=new Thread(r,"fake-codec-prep");t.setDaemon(true);return t;});
 static volatile int holdPreparation,rejectPreparation;static final CountDownLatch prepEntered=new CountDownLatch(1),prepRelease=new CountDownLatch(1);
 static final ExecutorService rejecting=new AbstractExecutorService(){public void shutdown(){}public List<Runnable>shutdownNow(){return Collections.emptyList();}public boolean isShutdown(){return false;}public boolean isTerminated(){return false;}public boolean awaitTermination(long n,TimeUnit u){return false;}public void execute(Runnable r){throw new RejectedExecutionException("scripted prep rejection");}};
 static final CountDownLatch uiEntered=new CountDownLatch(1),uiRelease=new CountDownLatch(1);
 static class Photo{final Bitmap image;final int id,noise,rotation,direction;final boolean colour,fixed;final CountDownLatch processed=new CountDownLatch(1),saved=new CountDownLatch(1),codecReady=new CountDownLatch(1);final AtomicBoolean closePosted=new AtomicBoolean();volatile boolean abandoned;volatile androidx.heifwriter.HeifWriter writer;Photo(Bitmap b,int r,int d){image=b;id=ShotContext1932.forBitmap(b).id;noise=AsyncSave1935.settings(PhotoDetail.live).noiseLevel;colour=AsyncSave1935.chroma(ChromaPipeline177.live);fixed=SaveQuality2.isFixed245Enabled();rotation=r;direction=d;}}
 static void closeCodec(Photo p){if(p.closePosted.compareAndSet(false,true))CodecDrain1945.close(p.writer);}
 // The abandoned job can release its correction slot while still owning its
 // FIFO terminal turn. Control this fixture's intended idle-preparation case
 // at the actual queue boundary, not a receipt/counter or scheduler delay.
 static boolean previousCodecTurnFinished(){try{
  java.lang.reflect.Field queue=SaveQueue1935.class.getDeclaredField("jobs"),codec=SaveQueue1935.class.getDeclaredField("codec"),encoding=SaveQueue1935.class.getDeclaredField("encoding");
  queue.setAccessible(true);codec.setAccessible(true);encoding.setAccessible(true);
  synchronized(queue.get(null)){return codec.get(null)==null&&encoding.get(null)==null;}
 }catch(ReflectiveOperationException missing){throw new AssertionError(missing);}}
 public static String encode(i.o.a.q.c.c.b.e controller,Bitmap image,int rotation,int direction)throws Exception{
  Photo p=new Photo(image,rotation,direction);
  if(p.id==1202)await(SaveHarness1935::previousCodecTurnFinished,"previous FIFO terminal codec turn released before scripted idle preparation");
  AsyncSave1935.prepareCodec(p.id==rejectPreparation?rejecting:codecPrep,()->{try{p.writer=CodecDrain1945.build(new androidx.heifwriter.HeifWriter.Builder());if(p.id==holdPreparation){prepEntered.countDown();if(!prepRelease.await(5,TimeUnit.SECONDS))throw new AssertionError("prep hold timeout");}p.codecReady.countDown();if(p.abandoned)closeCodec(p);}catch(Exception e){throw new RuntimeException(e);}});
  preparing.add(p);if(!fast&&!p.processed.await(5,TimeUnit.SECONDS))throw new AssertionError("processing timeout");
  if(p.id==failureBeforeEncoding){p.abandoned=true;if(p.codecReady.getCount()==0)closeCodec(p);throw new IllegalStateException("scripted correction failure");}
  AsyncSave1935.encoding(image);if(!p.codecReady.await(5,TimeUnit.SECONDS))throw new AssertionError("codec prepare timeout");controller.e=p.id;controller.f=image.getHeight();int active=encoderActive.incrementAndGet();peak.accumulateAndGet(active,Math::max);encoding.add(p);
  try{if(!fast&&!p.saved.await(5,TimeUnit.SECONDS))throw new AssertionError("encoder timeout");if(image.isRecycled())throw new AssertionError("encoder pixels recycled");if(p.id==failureId)throw new IllegalStateException("scripted encode failure");return "photo-"+p.id;}finally{closeCodec(p);CodecDrain1945.awaitClosed();encoderActive.decrementAndGet();}
 }
 static Photo next(BlockingQueue<Photo> q,String why)throws Exception{Photo p=q.poll(5,TimeUnit.SECONDS);check(p!=null,why);return p;}
 static void await(java.util.function.BooleanSupplier p,String why)throws Exception{long end=System.nanoTime()+5000000000L;while(!p.getAsBoolean()&&System.nanoTime()<end)Thread.sleep(2);check(p.getAsBoolean(),why);}
 static Bitmap source(int id,int n){Bitmap b=new Bitmap(new int[]{n,n+1,n+2,n+3});ShotContext1932.bind(b,id);i.f.l.n.s.a.b().image=b;return b;}
 public static class Camera{final int code;Camera(int code){this.code=code;}public int D1(){return code;}}
 static void fault(int mode)throws Exception{
  fast=true;
  if(mode==5){androidx.heifwriter.HeifWriter.Builder.mode=1;android.media.MediaCodec.failRelease=true;try{CodecDrain1945.build(new androidx.heifwriter.HeifWriter.Builder());throw new AssertionError("constructor failure required");}catch(java.io.IOException expected){}check(codecAllocated.get()==1,"unconfirmed failed constructor resource remains tracked");try{CodecDrain1945.build(new androidx.heifwriter.HeifWriter.Builder());throw new AssertionError("next constructor must be blocked");}catch(IllegalStateException expected){}check(codecAllocated.get()==1&&codecPeak.get()==1,"unconfirmed release prevents any second hardware constructor");System.out.println("PASS codec fault assertions="+assertions+" mode="+mode);return;}
  if(mode==4)android.media.MediaCodec.failRelease=true;else android.os.Handler.codecMode=mode;
  i.o.a.b1.a.b.f.a manager=new i.o.a.b1.a.b.f.a(new i.o.a.b1.a.b.f.a.c(){public void a(){finishes++;}public void b(boolean ok,int id,String path,String error){completed.add(ok?path:"failure");}});
  source(1600+mode,160);AsyncSave1935.submitAuto(manager,0,0);next(preparing,"fault photo enters correction");next(encoding,"fault photo enters encoder");await(()->SaveQueue1935.count()==0&&ExitJobs185.count()==0,"callback failure contains OOM/link and balances save/exit ownership");check(completed.equals(Arrays.asList("failure")),"callback failure reports failed terminal receipt");check(SaveQueue1935.maximumPixels()==0&&SaveQueue1935.nativeBytes()==0,"callback failure releases native cost and source ownership");try{CodecDrain1945.build(new androidx.heifwriter.HeifWriter.Builder());throw new AssertionError("failed callback must block new constructor");}catch(IllegalStateException expected){}check(codecPeak.get()==1,"unconfirmed callback/resource close cannot allocate second codec");System.out.println("PASS codec fault assertions="+assertions+" mode="+mode);
 }
 public static void main(String[]args)throws Exception{
  if(args.length>0){fault(Integer.parseInt(args[0]));return;}
  i.o.a.b1.a.b.f.a manager=new i.o.a.b1.a.b.f.a(new i.o.a.b1.a.b.f.a.c(){public void a(){finishes++;}public void b(boolean ok,int id,String path,String error){if(ok)check(path.equals("photo-"+id),"receipt controller bound to exact saved photo");completed.add(ok?path:"failure");if(path.equals("photo-101")){uiEntered.countDown();try{if(!uiRelease.await(5,TimeUnit.SECONDS))throw new AssertionError("UI hold timeout");}catch(InterruptedException e){throw new AssertionError(e);}}}});
  Bitmap firstSource=source(101,11);AsyncSave1935.submitAuto(manager,90,2);Photo one=next(preparing,"first preparation");await(()->finishes==1,"capture released before final correction");check(SaveQueue1935.nativeBytes()==32,"input plus anticipated final native bitmaps explicitly budgeted");check(!SaveQueue1935.memoryAllows(SaveQueue1935.nativeBytes()+SaveQueue1935.RESERVE+95,4),"queued native bitmap bytes subtracted from Java headroom");check(SaveQueue1935.memoryAllows(SaveQueue1935.nativeBytes()+SaveQueue1935.RESERVE+96,4),"tracked native allocation exact safe bound");check(!AsyncSave1935.captureBlocked(),"second real capture accepted during first correction");SaveQuality2.MemoryManager.low=true;check(AsyncSave1935.captureBlocked(),"physical low-memory signal blocks overlapping capture");SaveQuality2.MemoryManager.low=false;check(!AsyncSave1935.captureBlocked(),"physical memory recovery restores safe capture admission");CaptureYuv.state.yuv.w=6000;CaptureYuv.state.yuv.h=4000;check(AsyncSave1935.captureBlocked(),"current larger reader geometry budgets concurrent reserve");CaptureYuv.state.yuv.w=2;CaptureYuv.state.yuv.h=2;CaptureYuv.ready=false;check(AsyncSave1935.captureBlocked(),"reconfiguring reader never overlaps");CaptureYuv.ready=true;CaptureYuv.state.yuv.format=256;check(AsyncSave1935.captureBlocked(),"unverified input route remains serial");CaptureYuv.state.yuv.format=35;
  check(one.codecReady.await(5,TimeUnit.SECONDS),"idle first codec prepared during correction");check(codecAllocated.get()==1,"early preparation owns hardware without releasing correction");
  check(one.image!=firstSource,"independent exact owned pixels");firstSource.pixels[0]=999;check(one.image.pixels[0]==11,"renderer source reuse cannot corrupt photo");
  PhotoDetail.live=new PhotoDetail.Settings(3);ChromaPipeline177.live=false;SaveQuality2.live=false;source(202,21);AsyncSave1935.submitAuto(manager,270,1);await(()->finishes==2,"second copied capture released without waiting for first save");check(preparing.isEmpty(),"only one correction stage before encoding boundary");
  one.processed.countDown();Photo firstEncoder=next(encoding,"first encode");check(firstEncoder==one,"same final owned image");Photo two=next(preparing,"second correction overlaps first encoder");check(encoderActive.get()==1,"encoder active while next correction works");check(two.codecReady.getCount()==1,"occupied codec defers next constructor during correction");
  PhotoDetail.live=new PhotoDetail.Settings(4);ChromaPipeline177.live=true;SaveQuality2.live=true;source(303,31);AsyncSave1935.submitAuto(manager,180,3);await(()->finishes==3,"third captured waiting slot");check(SaveQueue1935.count()==3,"three bounded photo ownerships");check(AsyncSave1935.captureBlocked(),"fourth shutter blocked at real photo capacity");check(SaveQueue1935.maximumPixels()==4,"pending geometry accounted");
  two.processed.countDown();Thread.sleep(30);check(encoding.isEmpty(),"second encoder waits for first close");check(preparing.isEmpty(),"third correction waits for occupied correction boundary");
  one.saved.countDown();check(uiEntered.await(5,TimeUnit.SECONDS),"first UI completion deliberately held");Photo secondEncoder=next(encoding,"second encoding proceeds despite blocked completion UI");check(secondEncoder==two,"second exact pixels");Photo three=next(preparing,"third correction overlaps second encode");
  check(one.noise==1&&one.colour&&one.fixed,"first captured options immutable");check(two.noise==3&&!two.colour&&!two.fixed,"second captured options immutable");check(three.noise==4&&three.colour&&three.fixed,"third captured options immutable");check(one.rotation==90&&one.direction==2&&two.rotation==270&&two.direction==1,"native orientation ordering unchanged");check(one.image.isRecycled(),"first image freed only after saved close");
  three.processed.countDown();two.saved.countDown();Photo thirdEncoder=next(encoding,"third encoding without blocked UI dependency");check(thirdEncoder==three,"FIFO encode identity");three.saved.countDown();await(()->SaveQueue1935.count()==0,"save ownership released after file completion independent of UI");check(ExitJobs185.count()==3,"all pending completion callbacks retain exit guard");check(peak.get()==1,"hardware encoder never concurrent");check(codecPeak.get()==1,"codec constructor guarded before allocation");check(completed.equals(Arrays.asList("photo-101")),"main UI callbacks remain FIFO");
  uiRelease.countDown();await(()->ExitJobs185.count()==0,"exit guard held through final UI completion");check(completed.equals(Arrays.asList("photo-101","photo-202","photo-303")),"ordered exact receipts");check(finishes==3,"capture finished exactly once per shot");
  int receiptStart=completed.size();fast=false;source(808,81);AsyncSave1935.submitAuto(manager,0,0);Photo orderedA=next(preparing,"FIFO failure prior photo correction");orderedA.processed.countDown();next(encoding,"FIFO failure prior encoder active");await(()->!AsyncSave1935.captureBlocked(),"capture ready for early failing correction");failureBeforeEncoding=909;source(909,91);AsyncSave1935.submitAuto(manager,0,0);Photo failedB=next(preparing,"second correction scheduled while prior encoder active");failedB.processed.countDown();Thread.sleep(40);check(completed.size()==receiptStart,"early correction failure cannot overtake prior writer receipt");check(SaveQueue1935.count()==2,"failed correction retains FIFO terminal turn");orderedA.saved.countDown();await(()->ExitJobs185.count()==0,"early correction failure drains in terminal order");check(completed.subList(receiptStart,completed.size()).equals(Arrays.asList("photo-808","failure")),"success and early correction failure receipts FIFO");check(failedB.image.isRecycled(),"failed correction exact input released");failureBeforeEncoding=0;
  fast=true;failureId=404;source(404,41);AsyncSave1935.submitAuto(manager,0,0);next(preparing,"failed preparation enters");next(encoding,"failed encoder enters");await(()->ExitJobs185.count()==0,"failed encode balances queue and UI guard");check(completed.get(completed.size()-1).equals("failure"),"failed save notified as failure");check(SaveQueue1935.count()==0,"failed slot freed");failureId=0;
  Bitmap borrowed=source(505,51);Bitmap.failCopy=true;int before=finishes;fast=false;AsyncSave1935.submitAuto(manager,0,0);Photo serial=next(preparing,"copy OOM serial exact fallback");check(serial.image==borrowed,"copy OOM retains pristine exact original");check(AsyncSave1935.captureBlocked(),"fallback source keeps shutter closed");check(finishes==before,"no early native callback in copy fallback");serial.processed.countDown();next(encoding,"serial fallback encode");serial.saved.countDown();await(()->ExitJobs185.count()==0,"serial fallback saved and notified");check(!borrowed.isRecycled(),"borrowed SDK bitmap never recycled");Bitmap.failCopy=false;
  fast=true;i.f.l.n.q.y.n.watermark=new Bitmap(new int[]{0x55});Bitmap markedSource=source(606,61);int copies=Bitmap.copies;AsyncSave1935.submitAuto(manager,0,0);Photo marked=next(preparing,"watermark direct owned preparation");next(encoding,"watermark encode");await(()->ExitJobs185.count()==0,"watermark completion");check(Bitmap.copies==copies,"no redundant full source copy for audited watermark route");check(marked.image!=markedSource,"watermark output owns separate image");check(markedSource.pixels[3]==64&&marked.image.pixels[3]==(64^0x55),"watermark input pristine and exact output");Bitmap hdr=source(607,62);hdr.gainmap=true;copies=Bitmap.copies;AsyncSave1935.submitAuto(manager,0,0);next(preparing,"gainmap route preparation");next(encoding,"gainmap route encode");await(()->ExitJobs185.count()==0,"gainmap completion");check(Bitmap.copies==copies+1,"gainmap preserves original copy route");
  Bitmap unpremult=source(608,63);unpremult.premult=false;copies=Bitmap.copies;AsyncSave1935.submitAuto(manager,0,0);next(preparing,"unpremult preparation");next(encoding,"unpremult encode");await(()->ExitJobs185.count()==0,"unpremult completion");check(Bitmap.copies==copies+1,"unpremult preserves original copy route");i.f.l.n.q.y.n.watermark=null;
  fast=false;SaveQuality2.live=false;source(1000,100);AsyncSave1935.submitAuto(manager,0,0);Photo nextTarget=next(preparing,"captured small output before preference switch");await(()->!AsyncSave1935.captureBlocked(),"small next planned output fits");SaveQuality2.largeFixed=true;SaveQuality2.live=true;check(AsyncSave1935.captureBlocked(),"current next fixed output target guard follows live preference change");SaveQuality2.largeFixed=false;nextTarget.processed.countDown();next(encoding,"previous photo fixed flag stays snapshotted");nextTarget.saved.countDown();await(()->ExitJobs185.count()==0,"planned next-target test balances");
  fast=false;SaveQuality2.largeFixed=true;source(1001,101);AsyncSave1935.submitAuto(manager,0,0);Photo fixed=next(preparing,"small input large fixed output preparation");check(SaveQueue1935.nativeBytes()==16+5712L*4284L*4L,"snapshot fixed245 target budgeted before normalize allocation");check(!SaveQueue1935.memoryAllows(SaveQueue1935.nativeBytes()+SaveQueue1935.RESERVE+95,4),"larger anticipated final allocation included in memory bound");fixed.processed.countDown();next(encoding,"fixed output encoder boundary");fixed.saved.countDown();await(()->ExitJobs185.count()==0,"large fixed output lease and memory cost released");SaveQuality2.largeFixed=false;fast=true;
  i.f.l.n.s.a.b().image=null;AsyncSave1935.submitAuto(manager,0,0);await(()->SaveQueue1935.count()==0,"missing source ownership cleanup");await(()->SaveQuality2.failures==1,"missing source failure shown");check(ExitJobs185.count()==0,"missing source exit guard balanced");
  check(!SaveQueue1935.memoryAllows(SaveQueue1935.RESERVE+95,4),"extra concurrent encoder reserve enforced below bound");check(SaveQueue1935.memoryAllows(SaveQueue1935.RESERVE+96,4),"safe exact memory bound");check(!SaveQueue1935.memoryAllows(Long.MAX_VALUE,32000001),"unknown large geometry serializes");check(AsyncSave1935.readiness(new Camera(7))==7,"native readiness errors retained");check(AsyncSave1935.readiness(new Camera(0))==0,"idle native readiness succeeds");
  for(int mode=1;mode<=3;mode++){android.os.Handler.mode=mode;source(700+mode,71);AsyncSave1935.submitAuto(manager,0,0);next(preparing,"failed main preparation");Photo e=next(encoding,"failed main encoder");await(()->SaveQueue1935.count()==0,"main failure saves and drains");await(()->ExitJobs185.count()==0,"main unavailable guard balances");check(e.image.isRecycled(),"main failure image freed");}
  android.os.Handler.mode=0;
  fast=false;holdPreparation=1201;failureBeforeEncoding=1201;int beforeFailure=completed.size();source(1201,120);AsyncSave1935.submitAuto(manager,0,0);Photo aborting=next(preparing,"early codec prepare before correction failure");check(prepEntered.await(5,TimeUnit.SECONDS),"running preparation constructor held");aborting.processed.countDown();Thread.sleep(40);check(SaveQueue1935.count()==1&&completed.size()==beforeFailure,"running abandoned producer keeps codec permit and terminal receipt");source(1202,121);AsyncSave1935.submitAuto(manager,0,0);Thread.sleep(40);check(preparing.isEmpty(),"next correction waits for abandoned constructor disposal");check(codecAllocated.get()==1,"no second constructor while abandoned producer running");prepRelease.countDown();Photo afterAbort=next(preparing,"next correction starts after abandoned codec close barrier");check(afterAbort.codecReady.await(5,TimeUnit.SECONDS),"new idle codec prepares after actual previous release");check(codecAllocated.get()==1&&codecPeak.get()==1,"nested front cleanup completed before next allocation");afterAbort.processed.countDown();next(encoding,"post-abandon next encode");afterAbort.saved.countDown();await(()->ExitJobs185.count()==0,"abandoned preparation balances exits");check(completed.subList(beforeFailure,completed.size()).equals(Arrays.asList("failure","photo-1202")),"abandoned producer maintains FIFO receipts");failureBeforeEncoding=0;holdPreparation=0;
  rejectPreparation=1301;int rejectedAt=completed.size();source(1301,130);AsyncSave1935.submitAuto(manager,0,0);await(()->ExitJobs185.count()==0&&completed.size()==rejectedAt+1,"PREP executor rejection releases all ownership and terminal receipt");check(completed.get(rejectedAt).equals("failure")&&codecAllocated.get()==0,"rejected constructor creates no codec and reports failure");rejectPreparation=0;
  androidx.heifwriter.HeifWriter legacy=CodecDrain1945.build(new androidx.heifwriter.HeifWriter.Builder());source(1401,140);AsyncSave1935.submitAuto(manager,0,0);Photo mixed=next(preparing,"legacy editing writer may coexist with queued correction");mixed.processed.countDown();Thread.sleep(40);check(encoding.isEmpty()&&codecAllocated.get()==1,"non-job legacy writer blocks queued constructor on shared hardware permit");CodecDrain1945.close(legacy);next(encoding,"queued writer starts only after legacy actual codec release");mixed.saved.countDown();await(()->ExitJobs185.count()==0,"mixed legacy and queued route completes");check(codecPeak.get()==1,"hardware codec never overlaps across non-job and job routes");
  Thread.currentThread().interrupt();androidx.heifwriter.HeifWriter interrupted=CodecDrain1945.build(new androidx.heifwriter.HeifWriter.Builder());check(Thread.currentThread().isInterrupted(),"codec acquire restores preexisting interrupt");CodecDrain1945.close(interrupted);check(Thread.currentThread().isInterrupted(),"close barrier completes before restoring interrupt");Thread.interrupted();
  for(int fault=1;fault<=3;fault++){androidx.heifwriter.HeifWriter.Builder.mode=fault;try{CodecDrain1945.build(new androidx.heifwriter.HeifWriter.Builder());throw new AssertionError("builder failure required");}catch(java.io.IOException|RuntimeException|OutOfMemoryError expected){}check(codecAllocated.get()==0,"failed builder releases actual allocated codec");androidx.heifwriter.HeifWriter retry=CodecDrain1945.build(new androidx.heifwriter.HeifWriter.Builder());check(codecAllocated.get()==1,"save can retry after confirmed constructor cleanup");CodecDrain1945.close(retry);}
  for(int fallback=4;fallback<=5;fallback++){androidx.heifwriter.HeifWriter.Builder.mode=fallback;androidx.heifwriter.HeifWriter fallbackWriter=CodecDrain1945.build(new androidx.heifwriter.HeifWriter.Builder());check(codecAllocated.get()==1&&codecPeak.get()==1,"constructor fallback releases first codec before allocating second");CodecDrain1945.close(fallbackWriter);}
  android.media.MediaCodec.failStop=true;androidx.heifwriter.HeifWriter stopFailed=CodecDrain1945.build(new androidx.heifwriter.HeifWriter.Builder());CodecDrain1945.close(stopFailed);check(codecAllocated.get()==0,"codec release always attempted when stop throws");androidx.heifwriter.HeifWriter stopRetry=CodecDrain1945.build(new androidx.heifwriter.HeifWriter.Builder());CodecDrain1945.close(stopRetry);check(codecAllocated.get()==0,"stop failure with confirmed release permits later retry");
  androidx.heifwriter.HeifWriter same=CodecDrain1945.build(new androidx.heifwriter.HeifWriter.Builder());androidx.heifwriter.HeifWriter.closingEntered=new CountDownLatch(1);androidx.heifwriter.HeifWriter.closingRelease=new CountDownLatch(1);AtomicReference<Throwable>raceError=new AtomicReference<Throwable>();AtomicReference<androidx.heifwriter.HeifWriter>newOwner=new AtomicReference<androidx.heifwriter.HeifWriter>();Thread closerA=new Thread(()->{try{CodecDrain1945.close(same);}catch(Throwable e){raceError.set(e);}}),closerB=new Thread(()->{try{CodecDrain1945.close(same);}catch(Throwable e){raceError.set(e);}}),builderB=new Thread(()->{try{newOwner.set(CodecDrain1945.build(new androidx.heifwriter.HeifWriter.Builder()));}catch(Throwable e){raceError.set(e);}});closerA.start();check(androidx.heifwriter.HeifWriter.closingEntered.await(5,TimeUnit.SECONDS),"first close owner holds actual close");closerB.start();builderB.start();Thread.sleep(40);check(closerB.isAlive()&&newOwner.get()==null&&codecAllocated.get()==1,"duplicate close waits and next builder retains hardware exclusion");androidx.heifwriter.HeifWriter.closingRelease.countDown();closerA.join(5000);closerB.join(5000);builderB.join(5000);androidx.heifwriter.HeifWriter.closingEntered=null;androidx.heifwriter.HeifWriter.closingRelease=null;check(raceError.get()==null&&newOwner.get()!=null&&codecAllocated.get()==1,"duplicate close cannot release the next writer codec");CodecDrain1945.close(same);check(codecAllocated.get()==1,"old unowned writer close cannot release active writer");CodecDrain1945.close(newOwner.get());check(codecAllocated.get()==0,"concurrent-close ownership fully released");
  AtomicInteger direct=new AtomicInteger();AsyncSave1935.prepareCodec(codecPrep,()->direct.incrementAndGet());await(()->direct.get()==1,"no-job editing route retains original executor dispatch");check(android.os.HandlerThread.created==1,"all photos reuse one dedicated callback thread");
  CountDownLatch callbackProbe=new CountDownLatch(1);CodecDrain1945.handler().post(()->{try{CodecDrain1945.awaitClosed();throw new AssertionError("callback wait must not block itself");}catch(IllegalStateException expected){callbackProbe.countDown();}});check(callbackProbe.await(5,TimeUnit.SECONDS),"callback-thread wait rejects self-deadlock");
  check(peak.get()==1&&codecPeak.get()==1&&codecAllocated.get()==0,"all failure paths release codec and keep allocation exclusive");await(()->SaveQueue1935.maximumPixels()==0&&SaveQueue1935.nativeBytes()==0,"completed geometry and native-cost references released");System.out.println("PASS save1945 assertions="+assertions+" scenarios=28 device_tested=false");
 }
}'''
    paths=[]
    for name,text in fixtures.items():
        p=work/'fixtures'/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(text);paths.append(p)
    classes=work/'classes';classes.mkdir(exist_ok=True)
    result=subprocess.run(['javac','-encoding','UTF-8','-source','8','-target','8','-d',str(classes),str(root/'AsyncSave1935.java'),str(root/'SaveQueue1935.java'),str(root/'ReflectionCache1945.java'),str(root/'CodecDrain1945.java')]+list(map(str,paths)),text=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT);(work/'compile.log').write_text(result.stdout)
    if result.returncode:raise RuntimeError(result.stdout)
    result=subprocess.run(['java','-Xmx256m','-cp',str(classes),'com.hiro.ulike.SaveHarness1935'],text=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,timeout=35);(work/'result.txt').write_text(result.stdout)
    if result.returncode:raise RuntimeError(result.stdout)
    count=int(result.stdout.split('assertions=')[1].split()[0])
    for mode in range(1,6):
        result=subprocess.run(['java','-Xmx256m','-cp',str(classes),'com.hiro.ulike.SaveHarness1935',str(mode)],text=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,timeout=20);(work/f'fault-{mode}.txt').write_text(result.stdout)
        if result.returncode:raise RuntimeError(result.stdout)
        count+=int(result.stdout.split('assertions=')[1].split()[0])
    data={'suite':'save1945','status':'passed','passed':True,'assertions':count,'scenarios':40,'device_tested':False,'idle_codec_prepare_overlaps_correction':True,'running_abandon_joined':True,'nested_front_close_barrier':True,'callback_threads':1,'media_store_direct_fd_preserved':True,'builder_failure_retry_after_confirmed_release':True,'constructor_fallback_single_codec':True,'stop_failure_always_releases':True,'duplicate_close_identity_exclusive':True,'unconfirmed_release_blocks_new_codec':True,'callback_post_oom_linkage_cleanup':True};(work/'result.json').write_text(json.dumps(data,indent=2));return data
if __name__=='__main__':
    import sys;print(json.dumps(test(Path(__file__).parent,Path(sys.argv[1])),indent=2))
