package com.hiro.ulike;
import java.io.*;
import java.lang.reflect.Method;
import java.util.Arrays;
public final class FinishGpu1952Test {
 private FinishGpu1952Test() {}
 private static int[] read(DataInputStream in,int n)throws Exception{
  int[] a=new int[n];for(int i=0;i<n;i++)a[i]=in.readInt();return a;
 }
 public static void main(String[] args)throws Exception{
  if(!GpuFinish1952.available())throw new AssertionError("H12 library unavailable");
  Method entry=GpuFinish1952.class.getDeclaredMethod("finishNative",int[].class,int[].class,
   int[].class,int.class,int.class,int.class,int.class,boolean.class,boolean.class,
   int.class,int.class,int.class,boolean.class,boolean.class,boolean.class);
  entry.setAccessible(true);long pixels=0;int cases=0,sequences=0,changes=0;
  for(int mode=0;mode<2;mode++)try(DataInputStream in=new DataInputStream(new BufferedInputStream(new FileInputStream(args[mode])))){
   while(in.available()>0){
    int w=in.readInt(),rows=in.readInt(),first=in.readInt(),last=in.readInt(),moire=in.readInt(),sharp=in.readInt();
    int gain=in.readInt(),floor=in.readInt(),limit=in.readInt(),texture=in.readInt(),halo=in.readInt(),origin=in.readInt();
    int n=w*rows;int[] source=read(in,n),expected=read(in,n),policy=read(in,Math.max(1,w*(last-first))*4);
    // The sequential endpoint is used only when both baseline stages are enabled.
    if(mode==1 && moire==0)continue;
    int[] actual=new int[n];Arrays.fill(actual,0x13579bdf);
    int[] original=source.clone();
    boolean ok=(Boolean)entry.invoke(null,source,actual,policy,w,rows,first,last,moire!=0,
     sharp!=0,gain,floor,limit,texture!=0,halo!=0,mode==1);
    if(!ok)throw new AssertionError("GLES/JNI route failed case="+cases+" shape="+w+"x"+rows+" mode="+mode);
    for(int i=0;i<n;i++)if(actual[i]!=expected[i])throw new AssertionError("Exact GLES pixels case="+cases+
     " mode="+mode+" x="+(i%w)+" y="+(i/w)+" e="+Integer.toHexString(expected[i])+" a="+Integer.toHexString(actual[i]));
    if(!Arrays.equals(source,original))throw new AssertionError("Source changed");
    for(int i=first*w;i<last*w;i++)if(actual[i]!=source[i])changes++;
    pixels+=n;cases++;if(mode==1)sequences++;
   }
  }
  // Production policy wrapper: every float/mask field is generated by Java.
  int w=119,rows=141,n=w*rows;int[] source=new int[n];
  for(int y=0;y<rows;y++)for(int x=0;x<w;x++){
   int g=126+(x+y)%7,r=g+(x%4<2?21:-21),b=g-(r-g),a=(x+y*13)%97==0?113:255;
   source[y*w+x]=(a<<24)|(r<<16)|(g<<8)|b;
  }
  QualityPixels1932.Plan plan=QualityPixels1932.plan(new QualityPixels1932.NoiseStats(1.7f,1.2f,128f,0f,200),
   800,15000000L,QualityPixels1932.LENS_WIDE,.8f,4,4,true,true,1f).withFaceRegions(new QualityPixels1932.RegionMask(){
    public int skinQ8(int x,int y){return (x*23+y*11)&511;}
    public int detailQ8(int x,int y){return 0;}
   });
  int[] expected=new int[n],actual=new int[n];Arrays.fill(expected,0x13579bdf);Arrays.fill(actual,0x13579bdf);
  QualityPixels1932.finishStripAtBefore1951(source,expected,w,rows,36,105,plan,true,true,87);
  if(!GpuFinish1952.rawFinishStrip(source,actual,w,rows,36,105,plan,true,true,87) || !Arrays.equals(expected,actual))
   throw new AssertionError("Production policy wrapper baseline-combined mismatch");
  int[] middle=new int[n];QualityPixels1932.finishStripAtBefore1951(source,middle,w,rows,0,rows,plan,true,false,87);
  Arrays.fill(expected,0x13579bdf);Arrays.fill(actual,0x13579bdf);
  QualityPixels1932.finishStripAtBefore1951(middle,expected,w,rows,36,105,plan,false,true,87);
  if(!GpuFinish1952.rawSequentialStrip(source,actual,w,rows,36,105,plan,87) || !Arrays.equals(expected,actual))
   throw new AssertionError("Production policy wrapper sequential mismatch");
  final Throwable[] failures=new Throwable[4];Thread[] threads=new Thread[4];
  for(int t=0;t<4;t++){final int which=t;threads[t]=new Thread(new Runnable(){public void run(){
   try {
    int width=93+which*7,height=107+which*9,count=width*height;
    int[] input=new int[count],oracle=new int[count],gpu=new int[count],mid=new int[count];
    for(int y=0;y<height;y++)for(int x=0;x<width;x++){
     int green=128+(x+y+which)%5,red=green+((x+which)%4<2?23:-23),blue=green-(red-green);
     input[y*width+x]=0xff000000|(red<<16)|(green<<8)|blue;
    }
    QualityPixels1932.Plan p=QualityPixels1932.plan(new QualityPixels1932.NoiseStats(.8f+which,1f,128f,0f,200),
     100,10000000L,QualityPixels1932.LENS_WIDE,0f,2,4,false,true,1f);
    QualityPixels1932.finishStripAtBefore1951(input,mid,width,height,0,height,p,true,false,which*59);
    QualityPixels1932.finishStripAtBefore1951(mid,oracle,width,height,0,height,p,false,true,which*59);
    if(!GpuFinish1952.rawSequentialStrip(input,gpu,width,height,0,height,p,which*59) || !Arrays.equals(oracle,gpu))
     throw new AssertionError("Concurrent capture mixed GPU workspace");
   }catch(Throwable failure){failures[which]=failure;}
  }});threads[t].start();}
  for(Thread t:threads)t.join();
  for(Throwable failure:failures)if(failure!=null)throw new AssertionError("Concurrent GPU failure",failure);
  int[] original=actual.clone();
  if(GpuFinish1952.rawFinishStrip(source,actual,0,rows,36,105,plan,true,true,0) || !Arrays.equals(original,actual))
   throw new AssertionError("Failed candidate published destination");
  Thread.currentThread().interrupt();
  if(GpuFinish1952.rawSequentialStrip(source,actual,w,rows,36,105,plan,0) || !Arrays.equals(original,actual))
   throw new AssertionError("Interrupted candidate published destination");
  Thread.interrupted();
  System.out.println("H12_JNI_PASS cases="+cases+" sequential="+sequences+" pixels="+pixels+" changed="+changes+
   " java_policy_exact=true fallback_unchanged=true source_immutable=true dependency_tiles=true concurrent_captures_exact=true");
 }
}
